import { foreignKey, index, integer, pgEnum, pgTable, text, timestamp, uniqueIndex, varchar } from "drizzle-orm/pg-core";

export const userStatus = ["active", "disabled"] as const;
export const roleSlugs = ["admin", "systems_network_admin", "technician", "it_manager", "user"] as const;
export const assetTypes = ["server", "workstation", "network_device"] as const;
export const assetStatuses = ["ACTIVE", "INACTIVE", "MAINTENANCE", "RETIRED", "UNKNOWN"] as const;
export const environments = ["PRODUCTION", "DEVELOPMENT", "TEST", "LAB", "OTHER"] as const;
export const monitoringTypes = ["NODE_EXPORTER", "WINDOWS_EXPORTER", "SNMP", "DOCKER", "PROXMOX", "CUSTOM"] as const;
export const monitoringStatuses = ["NOT_CONFIGURED", "CONFIGURED", "UP", "DOWN", "UNKNOWN"] as const;
export const alertSeverities = ["INFO", "WARNING", "CRITICAL"] as const;
export const alertStatuses = ["PENDING", "FIRING", "RESOLVED", "UNKNOWN"] as const;
export const incidentStatuses = ["OPEN", "ACKNOWLEDGED", "IN_PROGRESS", "RESOLVED", "CLOSED"] as const;

export const userStatusEnum = pgEnum("user_status", userStatus);
export const assetTypeEnum = pgEnum("asset_type", assetTypes);
export const assetStatusEnum = pgEnum("asset_status", assetStatuses);
export const environmentEnum = pgEnum("environment", environments);
export const monitoringTypeEnum = pgEnum("monitoring_type", monitoringTypes);
export const monitoringStatusEnum = pgEnum("monitoring_status", monitoringStatuses);
export const alertSeverityEnum = pgEnum("alert_severity", alertSeverities);
export const alertStatusEnum = pgEnum("alert_status", alertStatuses);
export const incidentStatusEnum = pgEnum("incident_status", incidentStatuses);

export const roles = pgTable("roles", { id: integer("id").generatedByDefaultAsIdentity().primaryKey(), slug: varchar("slug", { length: 64 }).notNull(), name: varchar("name", { length: 128 }).notNull(), description: text("description"), createdAt: timestamp("createdAt").defaultNow().notNull() }, table => ({ slugUnique: uniqueIndex("roles_slug_unique").on(table.slug) }));
export const permissions = pgTable("permissions", { id: integer("id").generatedByDefaultAsIdentity().primaryKey(), slug: varchar("slug", { length: 128 }).notNull(), name: varchar("name", { length: 128 }).notNull(), description: text("description") }, table => ({ slugUnique: uniqueIndex("permissions_slug_unique").on(table.slug) }));
export const users = pgTable("users", { id: integer("id").generatedByDefaultAsIdentity().primaryKey(), openId: varchar("openId", { length: 128 }).notNull().unique(), name: varchar("name", { length: 255 }), email: varchar("email", { length: 320 }), loginMethod: varchar("loginMethod", { length: 64 }), role: varchar("role", { length: 64 }).default("user").notNull(), status: userStatusEnum("status").default("active").notNull(), createdAt: timestamp("createdAt").defaultNow().notNull(), updatedAt: timestamp("updatedAt").defaultNow().notNull(), lastSignedIn: timestamp("lastSignedIn").defaultNow().notNull(), disabledAt: timestamp("disabledAt") }, table => ({ emailIdx: index("users_email_idx").on(table.email), roleIdx: index("users_role_idx").on(table.role), statusIdx: index("users_status_idx").on(table.status), roleFk: foreignKey({ columns: [table.role], foreignColumns: [roles.slug], name: "users_role_fk" }).onDelete("restrict") }));
export const rolePermissions = pgTable("role_permissions", { roleId: integer("roleId").notNull(), permissionId: integer("permissionId").notNull() }, table => ({ compositeUnique: uniqueIndex("role_permissions_unique").on(table.roleId, table.permissionId), roleFk: foreignKey({ columns: [table.roleId], foreignColumns: [roles.id], name: "role_permissions_role_fk" }).onDelete("cascade"), permissionFk: foreignKey({ columns: [table.permissionId], foreignColumns: [permissions.id], name: "role_permissions_permission_fk" }).onDelete("cascade") }));
export const auditLogs = pgTable("audit_logs", { id: integer("id").generatedByDefaultAsIdentity().primaryKey(), actorUserId: integer("actorUserId"), action: varchar("action", { length: 128 }).notNull(), targetType: varchar("targetType", { length: 64 }), targetId: varchar("targetId", { length: 128 }), metadata: text("metadata"), ipAddress: varchar("ipAddress", { length: 64 }), userAgent: text("userAgent"), createdAt: timestamp("createdAt").defaultNow().notNull() }, table => ({ actorIdx: index("audit_logs_actor_idx").on(table.actorUserId), actionIdx: index("audit_logs_action_idx").on(table.action), actorFk: foreignKey({ columns: [table.actorUserId], foreignColumns: [users.id], name: "audit_logs_actor_fk" }).onDelete("set null") }));

export const locations = pgTable("locations", { id: integer("id").generatedByDefaultAsIdentity().primaryKey(), name: varchar("name", { length: 160 }).notNull(), kind: varchar("kind", { length: 64 }).notNull().default("site"), address: text("address"), description: text("description"), createdAt: timestamp("createdAt").defaultNow().notNull(), updatedAt: timestamp("updatedAt").defaultNow().notNull() }, table => ({ nameUnique: uniqueIndex("locations_name_unique").on(table.name), kindIdx: index("locations_kind_idx").on(table.kind) }));

export const assets = pgTable("assets", { id: integer("id").generatedByDefaultAsIdentity().primaryKey(), assetTag: varchar("assetTag", { length: 128 }).notNull(), hostname: varchar("hostname", { length: 255 }), displayName: varchar("displayName", { length: 255 }).notNull(), description: text("description"), serialNumber: varchar("serialNumber", { length: 255 }), assetType: assetTypeEnum("assetType").notNull(), primaryIp: varchar("primaryIp", { length: 64 }), primaryMac: varchar("primaryMac", { length: 32 }), domain: varchar("domain", { length: 255 }), fqdn: varchar("fqdn", { length: 255 }), os: varchar("os", { length: 128 }), osDistribution: varchar("osDistribution", { length: 128 }), osVersion: varchar("osVersion", { length: 128 }), architecture: varchar("architecture", { length: 64 }), kernelVersion: varchar("kernelVersion", { length: 128 }), environment: environmentEnum("environment").default("OTHER").notNull(), role: varchar("role", { length: 128 }), locationId: integer("locationId"), status: assetStatusEnum("status").default("UNKNOWN").notNull(), manufacturer: varchar("manufacturer", { length: 128 }), model: varchar("model", { length: 128 }), cpuCores: integer("cpuCores"), memoryMb: integer("memoryMb"), storageGb: integer("storageGb"), notes: text("notes"), createdAt: timestamp("createdAt").defaultNow().notNull(), updatedAt: timestamp("updatedAt").defaultNow().notNull() }, table => ({ assetTagUnique: uniqueIndex("assets_asset_tag_unique").on(table.assetTag), hostnameIdx: index("assets_hostname_idx").on(table.hostname), serialIdx: index("assets_serial_idx").on(table.serialNumber), typeIdx: index("assets_type_idx").on(table.assetType), statusIdx: index("assets_status_idx").on(table.status), environmentIdx: index("assets_environment_idx").on(table.environment), locationIdx: index("assets_location_idx").on(table.locationId), locationFk: foreignKey({ columns: [table.locationId], foreignColumns: [locations.id], name: "assets_location_fk" }).onDelete("restrict") }));

export const servers = pgTable("servers", { assetId: integer("assetId").primaryKey(), serverType: varchar("serverType", { length: 128 }), notes: text("notes") }, table => ({ assetFk: foreignKey({ columns: [table.assetId], foreignColumns: [assets.id], name: "servers_asset_fk" }).onDelete("cascade") }));
export const workstations = pgTable("workstations", { assetId: integer("assetId").primaryKey(), primaryUserId: integer("primaryUserId"), purchaseDate: timestamp("purchaseDate"), warrantyUntil: timestamp("warrantyUntil"), notes: text("notes") }, table => ({ assetFk: foreignKey({ columns: [table.assetId], foreignColumns: [assets.id], name: "workstations_asset_fk" }).onDelete("cascade"), userFk: foreignKey({ columns: [table.primaryUserId], foreignColumns: [users.id], name: "workstations_user_fk" }).onDelete("set null"), userIdx: index("workstations_user_idx").on(table.primaryUserId) }));
export const networkDevices = pgTable("network_devices", { assetId: integer("assetId").primaryKey(), deviceType: varchar("deviceType", { length: 128 }).notNull(), firmware: varchar("firmware", { length: 128 }), notes: text("notes") }, table => ({ assetFk: foreignKey({ columns: [table.assetId], foreignColumns: [assets.id], name: "network_devices_asset_fk" }).onDelete("cascade") }));

export const networkInterfaces = pgTable("network_interfaces", { id: integer("id").generatedByDefaultAsIdentity().primaryKey(), assetId: integer("assetId").notNull(), name: varchar("name", { length: 128 }).notNull(), interfaceType: varchar("interfaceType", { length: 64 }), macAddress: varchar("macAddress", { length: 32 }), ipAddress: varchar("ipAddress", { length: 64 }), prefix: varchar("prefix", { length: 32 }), vlan: integer("vlan"), speedMbps: integer("speedMbps"), administrativeState: varchar("administrativeState", { length: 32 }), operationalState: varchar("operationalState", { length: 32 }), description: text("description") }, table => ({ assetNameUnique: uniqueIndex("network_interfaces_asset_name_unique").on(table.assetId, table.name), assetIdx: index("network_interfaces_asset_idx").on(table.assetId), ipIdx: index("network_interfaces_ip_idx").on(table.ipAddress), assetFk: foreignKey({ columns: [table.assetId], foreignColumns: [assets.id], name: "network_interfaces_asset_fk" }).onDelete("cascade") }));

export const software = pgTable("software", { id: integer("id").generatedByDefaultAsIdentity().primaryKey(), name: varchar("name", { length: 255 }).notNull(), vendor: varchar("vendor", { length: 160 }), version: varchar("version", { length: 128 }), category: varchar("category", { length: 128 }), license: varchar("license", { length: 128 }), status: varchar("status", { length: 64 }).notNull().default("ACTIVE"), description: text("description"), createdAt: timestamp("createdAt").defaultNow().notNull(), updatedAt: timestamp("updatedAt").defaultNow().notNull() }, table => ({ nameVersionUnique: uniqueIndex("software_name_version_unique").on(table.name, table.version), nameIdx: index("software_name_idx").on(table.name) }));
export const softwareInstallations = pgTable("software_installations", { id: integer("id").generatedByDefaultAsIdentity().primaryKey(), assetId: integer("assetId").notNull(), softwareId: integer("softwareId").notNull(), installedVersion: varchar("installedVersion", { length: 128 }), installedAt: timestamp("installedAt"), updatedAt: timestamp("updatedAt"), status: varchar("status", { length: 64 }).notNull().default("ACTIVE") }, table => ({ assetSoftwareUnique: uniqueIndex("software_install_asset_unique").on(table.assetId, table.softwareId), assetFk: foreignKey({ columns: [table.assetId], foreignColumns: [assets.id], name: "software_install_asset_fk" }).onDelete("cascade"), softwareFk: foreignKey({ columns: [table.softwareId], foreignColumns: [software.id], name: "software_install_software_fk" }).onDelete("cascade"), assetIdx: index("software_install_asset_idx").on(table.assetId), softwareIdx: index("software_install_software_idx").on(table.softwareId) }));

export const assetRelationships = pgTable("asset_relationships", { id: integer("id").generatedByDefaultAsIdentity().primaryKey(), sourceAssetId: integer("sourceAssetId").notNull(), destinationAssetId: integer("destinationAssetId").notNull(), relationshipType: varchar("relationshipType", { length: 64 }).notNull(), sourceInterfaceId: integer("sourceInterfaceId"), destinationInterfaceId: integer("destinationInterfaceId"), description: text("description"), createdAt: timestamp("createdAt").defaultNow().notNull() }, table => ({ relationUnique: uniqueIndex("asset_relationship_unique").on(table.sourceAssetId, table.destinationAssetId, table.relationshipType), sourceIdx: index("asset_relationship_source_idx").on(table.sourceAssetId), destinationIdx: index("asset_relationship_destination_idx").on(table.destinationAssetId), sourceFk: foreignKey({ columns: [table.sourceAssetId], foreignColumns: [assets.id], name: "asset_relationship_source_fk" }).onDelete("cascade"), destinationFk: foreignKey({ columns: [table.destinationAssetId], foreignColumns: [assets.id], name: "asset_relationship_destination_fk" }).onDelete("restrict"), sourceInterfaceFk: foreignKey({ columns: [table.sourceInterfaceId], foreignColumns: [networkInterfaces.id], name: "asset_relationship_source_interface_fk" }).onDelete("set null"), destinationInterfaceFk: foreignKey({ columns: [table.destinationInterfaceId], foreignColumns: [networkInterfaces.id], name: "asset_relationship_destination_interface_fk" }).onDelete("set null") }));

export const monitoringTargets = pgTable("monitoring_targets", { id: integer("id").generatedByDefaultAsIdentity().primaryKey(), assetId: integer("assetId").notNull(), type: monitoringTypeEnum("type").notNull().default("NODE_EXPORTER"), endpoint: varchar("endpoint", { length: 255 }).notNull(), port: integer("port").notNull().default(9100), enabled: integer("enabled").notNull().default(0), status: monitoringStatusEnum("status").notNull().default("NOT_CONFIGURED"), labels: text("labels"), lastObservedAt: timestamp("lastObservedAt"), createdAt: timestamp("createdAt").defaultNow().notNull(), updatedAt: timestamp("updatedAt").defaultNow().notNull() }, table => ({ assetTypeUnique: uniqueIndex("monitoring_targets_asset_type_endpoint_unique").on(table.assetId, table.type, table.endpoint, table.port), assetIdx: index("monitoring_targets_asset_idx").on(table.assetId), statusIdx: index("monitoring_targets_status_idx").on(table.status), enabledIdx: index("monitoring_targets_enabled_idx").on(table.enabled), assetFk: foreignKey({ columns: [table.assetId], foreignColumns: [assets.id], name: "monitoring_targets_asset_fk" }).onDelete("cascade") }));

export const alertRules = pgTable("alert_rules", { id: integer("id").generatedByDefaultAsIdentity().primaryKey(), name: varchar("name", { length: 160 }).notNull(), description: text("description"), expression: text("expression").notNull(), severity: alertSeverityEnum("severity").notNull().default("WARNING"), forDurationSeconds: integer("forDurationSeconds").notNull().default(300), enabled: integer("enabled").notNull().default(1), labels: text("labels"), annotations: text("annotations"), createdAt: timestamp("createdAt").defaultNow().notNull(), updatedAt: timestamp("updatedAt").defaultNow().notNull() }, table => ({ nameUnique: uniqueIndex("alert_rules_name_unique").on(table.name), enabledIdx: index("alert_rules_enabled_idx").on(table.enabled), severityIdx: index("alert_rules_severity_idx").on(table.severity) }));
export const alerts = pgTable("alerts", { id: integer("id").generatedByDefaultAsIdentity().primaryKey(), ruleId: integer("ruleId").notNull(), monitoringTargetId: integer("monitoringTargetId"), fingerprint: varchar("fingerprint", { length: 128 }).notNull(), severity: alertSeverityEnum("severity").notNull(), status: alertStatusEnum("status").notNull().default("PENDING"), summary: varchar("summary", { length: 255 }).notNull(), description: text("description"), startedAt: timestamp("startedAt"), resolvedAt: timestamp("resolvedAt"), lastSeenAt: timestamp("lastSeenAt").defaultNow().notNull(), labels: text("labels"), annotations: text("annotations"), createdAt: timestamp("createdAt").defaultNow().notNull(), updatedAt: timestamp("updatedAt").defaultNow().notNull() }, table => ({ fingerprintUnique: uniqueIndex("alerts_fingerprint_unique").on(table.fingerprint), ruleIdx: index("alerts_rule_idx").on(table.ruleId), targetIdx: index("alerts_target_idx").on(table.monitoringTargetId), statusIdx: index("alerts_status_idx").on(table.status), ruleFk: foreignKey({ columns: [table.ruleId], foreignColumns: [alertRules.id], name: "alerts_rule_fk" }).onDelete("restrict"), targetFk: foreignKey({ columns: [table.monitoringTargetId], foreignColumns: [monitoringTargets.id], name: "alerts_target_fk" }).onDelete("set null") }));
export const incidents = pgTable("incidents", { id: integer("id").generatedByDefaultAsIdentity().primaryKey(), title: varchar("title", { length: 255 }).notNull(), description: text("description"), severity: alertSeverityEnum("severity").notNull().default("WARNING"), status: incidentStatusEnum("status").notNull().default("OPEN"), source: varchar("source", { length: 64 }).notNull().default("ALERT"), monitoringTargetId: integer("monitoringTargetId"), alertId: integer("alertId"), assignedToUserId: integer("assignedToUserId"), createdAt: timestamp("createdAt").defaultNow().notNull(), acknowledgedAt: timestamp("acknowledgedAt"), resolvedAt: timestamp("resolvedAt"), resolutionNotes: text("resolutionNotes"), updatedAt: timestamp("updatedAt").defaultNow().notNull() }, table => ({ statusIdx: index("incidents_status_idx").on(table.status), severityIdx: index("incidents_severity_idx").on(table.severity), targetIdx: index("incidents_target_idx").on(table.monitoringTargetId), assigneeIdx: index("incidents_assignee_idx").on(table.assignedToUserId), alertIdx: index("incidents_alert_idx").on(table.alertId), targetFk: foreignKey({ columns: [table.monitoringTargetId], foreignColumns: [monitoringTargets.id], name: "incidents_target_fk" }).onDelete("set null"), alertFk: foreignKey({ columns: [table.alertId], foreignColumns: [alerts.id], name: "incidents_alert_fk" }).onDelete("set null"), assigneeFk: foreignKey({ columns: [table.assignedToUserId], foreignColumns: [users.id], name: "incidents_assignee_fk" }).onDelete("set null") }));
export const incidentHistory = pgTable("incident_history", { id: integer("id").generatedByDefaultAsIdentity().primaryKey(), incidentId: integer("incidentId").notNull(), actorUserId: integer("actorUserId"), action: varchar("action", { length: 64 }).notNull(), fromStatus: incidentStatusEnum("fromStatus"), toStatus: incidentStatusEnum("toStatus"), metadata: text("metadata"), createdAt: timestamp("createdAt").defaultNow().notNull() }, table => ({ incidentIdx: index("incident_history_incident_idx").on(table.incidentId), createdIdx: index("incident_history_created_idx").on(table.createdAt), incidentFk: foreignKey({ columns: [table.incidentId], foreignColumns: [incidents.id], name: "incident_history_incident_fk" }).onDelete("cascade"), actorFk: foreignKey({ columns: [table.actorUserId], foreignColumns: [users.id], name: "incident_history_actor_fk" }).onDelete("set null") }));

export type User = typeof users.$inferSelect;
export type InsertUser = typeof users.$inferInsert;
export type Role = typeof roles.$inferSelect;
export type Permission = typeof permissions.$inferSelect;
export type AuditLog = typeof auditLogs.$inferSelect;
export type Asset = typeof assets.$inferSelect;
export type InsertAsset = typeof assets.$inferInsert;
export type Location = typeof locations.$inferSelect;
export type Software = typeof software.$inferSelect;
export type AssetRelationship = typeof assetRelationships.$inferSelect;
export type MonitoringTarget = typeof monitoringTargets.$inferSelect;
export type InsertMonitoringTarget = typeof monitoringTargets.$inferInsert;
export type AlertRule = typeof alertRules.$inferSelect;
export type InsertAlertRule = typeof alertRules.$inferInsert;
export type Alert = typeof alerts.$inferSelect;
export type InsertAlert = typeof alerts.$inferInsert;
export type Incident = typeof incidents.$inferSelect;
export type InsertIncident = typeof incidents.$inferInsert;
export type IncidentHistory = typeof incidentHistory.$inferSelect;
