import { AlertTriangle, CheckCircle2, CircleAlert, Play, RefreshCw, SlidersHorizontal } from "lucide-react";
import { useState } from "react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { trpc } from "@/lib/trpc";

const tone: Record<string, string> = { INFO: "border-sky-200 bg-sky-50 text-sky-700", WARNING: "border-amber-200 bg-amber-50 text-amber-700", CRITICAL: "border-rose-200 bg-rose-50 text-rose-700", FIRING: "border-rose-200 bg-rose-50 text-rose-700", PENDING: "border-amber-200 bg-amber-50 text-amber-700", RESOLVED: "border-emerald-200 bg-emerald-50 text-emerald-700", UNKNOWN: "border-slate-200 bg-slate-100 text-slate-600" };
function Status({ value }: { value: string }) { return <Badge variant="outline" className={`rounded-full px-2.5 py-1 text-[10px] font-semibold tracking-[0.12em] ${tone[value] ?? "border-slate-200 bg-slate-50 text-slate-600"}`}>{value}</Badge>; }

export default function AlertsPage() {
  const rules = trpc.alertRules.list.useQuery();
  const alerts = trpc.alerts.list.useQuery();
  const bootstrap = trpc.alertRules.bootstrap.useMutation({ onSuccess: () => { void rules.refetch(); } });
  const [selectedRule, setSelectedRule] = useState<number | null>(null);
  const [selectedTarget, setSelectedTarget] = useState<number | null>(null);
  const sync = trpc.alerts.sync.useMutation({ onSuccess: () => { void alerts.refetch(); } });
  const targets = trpc.monitoring.targets.list.useQuery();
  const ruleItems = rules.data ?? [];
  const alertItems = alerts.data ?? [];
  const ruleById = new Map(ruleItems.map(rule => [rule.id, rule]));
  const targetById = new Map((targets.data ?? []).map(target => [target.id, target]));
  const apiError = rules.error || alerts.error || targets.error || bootstrap.error || sync.error;

  return <section className="space-y-8">
    <header className="flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div><p className="eyebrow">Control plane / alerting</p><h1 className="mt-3 text-4xl font-semibold tracking-[-0.04em] text-slate-950">Alerts</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-500">Les alertes sont des conditions évaluées par Prometheus. Elles ne deviennent des incidents qu’après corrélation selon une règle explicite.</p></div><div className="flex gap-2"><Button variant="outline" onClick={() => { void rules.refetch(); void alerts.refetch(); }}><RefreshCw className="mr-2 h-4 w-4" />Actualiser</Button><Button className="bg-slate-950 hover:bg-slate-800" onClick={() => bootstrap.mutate()} disabled={bootstrap.isPending}><SlidersHorizontal className="mr-2 h-4 w-4" />{bootstrap.isPending ? "Initialisation…" : "Charger les règles"}</Button></div></header>
    {apiError && <div className="rounded-2xl border border-rose-200 bg-rose-50 px-5 py-4 text-sm text-rose-700"><strong>API unavailable</strong><p className="mt-1">{apiError.message}</p></div>}
    <div className="grid gap-4 md:grid-cols-3"><Metric label="Firing" value={alerts.error ? "—" : alertItems.filter(item => item.status === "FIRING").length} icon={<CircleAlert className="h-5 w-5 text-rose-500" />} /><Metric label="Pending" value={alerts.error ? "—" : alertItems.filter(item => item.status === "PENDING").length} icon={<AlertTriangle className="h-5 w-5 text-amber-500" />} /><Metric label="Resolved" value={alerts.error ? "—" : alertItems.filter(item => item.status === "RESOLVED").length} icon={<CheckCircle2 className="h-5 w-5 text-emerald-500" />} /></div>
    <Card className="border-slate-200/80 shadow-sm"><CardHeader className="flex flex-row items-center justify-between"><div><p className="eyebrow">Prometheus metadata</p><CardTitle className="mt-2">Alert rules</CardTitle></div><span className="text-xs text-slate-400">{ruleItems.length} configurée(s)</span></CardHeader><CardContent>{rules.isLoading ? <p className="py-8 text-sm text-slate-500">Chargement des règles…</p> : ruleItems.length === 0 ? <Empty title="No alert rules" description="Aucune règle n’est persistée. Chargez les quatre règles Node Exporter de référence ou créez-les via l’API protégée." /> : <div className="divide-y divide-slate-100">{ruleItems.map(rule => <div key={rule.id} className="flex flex-col gap-3 py-4 lg:flex-row lg:items-center lg:justify-between"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><h3 className="font-medium text-slate-900">{rule.name}</h3><Status value={rule.severity} />{rule.enabled ? <Status value="ENABLED" /> : <Status value="UNKNOWN" />}</div><p className="mt-1 truncate font-mono text-xs text-slate-500">{rule.expression}</p><p className="mt-1 text-xs text-slate-400">for {rule.forDurationSeconds}s · {rule.enabled ? "active" : "disabled"}</p></div><Button variant="outline" size="sm" onClick={() => { setSelectedRule(rule.id); setSelectedTarget(targets.data?.[0]?.id ?? null); }}><Play className="mr-2 h-3.5 w-3.5" />Évaluer</Button></div>)}</div>}</CardContent></Card>
    {selectedRule && <Card className="border-slate-900 bg-slate-950 text-white"><CardContent className="flex flex-col gap-4 p-5 lg:flex-row lg:items-end"><div className="flex-1"><p className="text-[10px] font-semibold uppercase tracking-[0.18em] text-slate-400">Observation contrôlée</p><p className="mt-2 text-sm text-slate-300">L’évaluation interroge Prometheus avec la règle sélectionnée. Aucune métrique locale n’est simulée.</p></div><select aria-label="Monitoring target" value={selectedTarget ?? ""} onChange={event => setSelectedTarget(event.target.value ? Number(event.target.value) : null)} className="h-10 rounded-lg border border-white/15 bg-white/10 px-3 text-sm text-white"><option value="" className="text-slate-950">Sans cible</option>{(targets.data ?? []).map(target => <option key={target.id} value={target.id} className="text-slate-950">Target #{target.id} · {target.endpoint}</option>)}</select><Button onClick={() => sync.mutate({ ruleId: selectedRule, monitoringTargetId: selectedTarget })} disabled={sync.isPending} className="bg-white text-slate-950 hover:bg-slate-200">{sync.isPending ? "Évaluation…" : "Lancer l’évaluation"}</Button></CardContent></Card>}
    <Card className="border-slate-200/80 shadow-sm"><CardHeader className="flex flex-row items-center justify-between"><div><p className="eyebrow">Observed state</p><CardTitle className="mt-2">Alertes actives et historiques</CardTitle></div><span className="text-xs text-slate-400">{alertItems.length} observée(s)</span></CardHeader><CardContent>{alerts.isLoading ? <p className="py-8 text-sm text-slate-500">Lecture de Prometheus et des alertes persistées…</p> : alerts.error ? <Empty title="Prometheus unavailable" description="La lecture des alertes a échoué ; les compteurs ne sont pas interprétés comme zéro." /> : alertItems.length === 0 ? <Empty title="No alert data" description="Aucune alerte persistée n’est disponible. Une absence de données n’est pas interprétée comme une résolution." /> : <div className="space-y-3">{alertItems.map(alert => <div key={alert.id} className="rounded-2xl border border-slate-200 p-4"><div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><div><div className="flex flex-wrap items-center gap-2"><span className="font-medium text-slate-900">{alert.summary}</span><Status value={alert.severity} /><Status value={alert.status} /></div><p className="mt-2 text-sm text-slate-500">Règle : {ruleById.get(alert.ruleId)?.name ?? `Rule #${alert.ruleId}`} · Cible : {alert.monitoringTargetId ? targetById.get(alert.monitoringTargetId)?.endpoint ?? `Target #${alert.monitoringTargetId}` : "Sans cible"}</p><p className="mt-1 text-xs text-slate-400">Fingerprint <code className="rounded bg-slate-100 px-1.5 py-0.5 text-xs">{alert.fingerprint.slice(0, 16)}…</code> · {alert.status === "FIRING" ? `Firing depuis ${formatAge(alert.startedAt ?? alert.lastSeenAt)}` : `Dernière observation ${formatAge(alert.lastSeenAt)}`}</p></div><div className="text-right text-xs text-slate-400"><p className="font-medium text-slate-600">{alert.status === "FIRING" ? "Firing" : alert.status}</p><p className="mt-1">Vu le {new Date(alert.lastSeenAt).toLocaleString()}</p></div></div></div>)}</div>}</CardContent></Card>
  </section>;
}
function formatAge(value: Date | string | number) { const seconds = Math.max(0, Math.floor((Date.now() - new Date(value).getTime()) / 1000)); if (seconds < 60) return `${seconds}s`; const minutes = Math.floor(seconds / 60); if (minutes < 60) return `${minutes}min`; return `${Math.floor(minutes / 60)}h ${minutes % 60}min`; }
function Metric({ label, value, icon }: { label: string; value: number | string; icon: React.ReactNode }) { return <Card className="border-slate-200/80 shadow-sm"><CardContent className="flex items-center justify-between p-5"><div><p className="eyebrow">{label}</p><p className="mt-2 text-3xl font-semibold tracking-tight text-slate-950">{value}</p></div>{icon}</CardContent></Card>; }
function Empty({ title, description }: { title: string; description: string }) { return <div className="py-8 text-center"><p className="font-medium text-slate-800">{title}</p><p className="mx-auto mt-2 max-w-lg text-sm leading-6 text-slate-500">{description}</p></div>; }
