import { ArrowLeft, CheckCircle2, Clock3, Filter, Loader2, Lock, RefreshCw, UserRound } from "lucide-react";
import { useMemo, useState } from "react";
import { Link, useRoute } from "wouter";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { trpc } from "@/lib/trpc";
import { useAuth } from "@/_core/hooks/useAuth";
import { formatIncidentCode } from "./alertingPresentation";

const tone: Record<string, string> = { INFO: "border-sky-200 bg-sky-50 text-sky-700", WARNING: "border-amber-200 bg-amber-50 text-amber-700", CRITICAL: "border-rose-200 bg-rose-50 text-rose-700", OPEN: "border-rose-200 bg-rose-50 text-rose-700", ACKNOWLEDGED: "border-violet-200 bg-violet-50 text-violet-700", IN_PROGRESS: "border-sky-200 bg-sky-50 text-sky-700", RESOLVED: "border-emerald-200 bg-emerald-50 text-emerald-700", CLOSED: "border-slate-200 bg-slate-100 text-slate-600" };
function Status({ value }: { value: string }) { return <Badge variant="outline" className={`rounded-full px-2.5 py-1 text-[10px] font-semibold tracking-[0.12em] ${tone[value] ?? "border-slate-200 bg-slate-50 text-slate-600"}`}>{value}</Badge>; }

export default function IncidentsPage() {
  const [, params] = useRoute("/incidents/:id");
  return params?.id ? <IncidentDetail id={Number(params.id)} /> : <IncidentList />;
}
function IncidentList() {
  const [filters, setFilters] = useState<{ status?: "OPEN" | "ACKNOWLEDGED" | "IN_PROGRESS" | "RESOLVED" | "CLOSED"; severity?: "INFO" | "WARNING" | "CRITICAL"; assignedToUserId?: number; monitoringTargetId?: number; createdFrom?: string; createdTo?: string }>({});
  const queryFilters = useMemo(() => ({ status: filters.status, severity: filters.severity, assignedToUserId: filters.assignedToUserId, monitoringTargetId: filters.monitoringTargetId, createdFrom: filters.createdFrom ? new Date(`${filters.createdFrom}T00:00:00.000Z`) : undefined, createdTo: filters.createdTo ? new Date(`${filters.createdTo}T23:59:59.999Z`) : undefined }), [filters]);
  const incidents = trpc.incidents.list.useQuery(queryFilters);
  const targets = trpc.monitoring.targets.list.useQuery();
  const items = incidents.data ?? [];
  return <section className="space-y-8"><header className="flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div><p className="eyebrow">Control plane / response</p><h1 className="mt-3 text-4xl font-semibold tracking-[-0.04em] text-slate-950">Incidents</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-500">Un incident représente une intervention humaine. Les tickets, notifications externes et automatisations correctives restent hors périmètre de cette étape.</p></div><Button variant="outline" onClick={() => void incidents.refetch()}><RefreshCw className="mr-2 h-4 w-4" />Actualiser</Button></header>
    <Card className="border-slate-200/80 shadow-sm"><CardContent className="flex flex-col gap-3 p-4 md:flex-row md:items-center"><Filter className="h-4 w-4 text-slate-400" /><select aria-label="Filtrer par statut" value={filters.status ?? ""} onChange={event => setFilters(current => ({ ...current, status: (event.target.value || undefined) as typeof current.status }))} className="h-10 rounded-lg border border-slate-200 bg-white px-3 text-sm text-slate-700"><option value="">Tous les statuts</option>{["OPEN", "ACKNOWLEDGED", "IN_PROGRESS", "RESOLVED", "CLOSED"].map(value => <option key={value}>{value}</option>)}</select><select aria-label="Filtrer par sévérité" value={filters.severity ?? ""} onChange={event => setFilters(current => ({ ...current, severity: (event.target.value || undefined) as typeof current.severity }))} className="h-10 rounded-lg border border-slate-200 bg-white px-3 text-sm text-slate-700"><option value="">Toutes les sévérités</option>{["INFO", "WARNING", "CRITICAL"].map(value => <option key={value}>{value}</option>)}</select><select aria-label="Filtrer par monitoring target" value={filters.monitoringTargetId ?? ""} onChange={event => setFilters(current => ({ ...current, monitoringTargetId: event.target.value ? Number(event.target.value) : undefined }))} className="h-10 rounded-lg border border-slate-200 bg-white px-3 text-sm text-slate-700"><option value="">Toutes les cibles</option>{(targets.data ?? []).map(target => <option key={target.id} value={target.id}>Target #{target.id} · {target.endpoint}</option>)}</select><input aria-label="Filtrer par utilisateur assigné" type="number" min="1" placeholder="Utilisateur ID" value={filters.assignedToUserId ?? ""} onChange={event => setFilters(current => ({ ...current, assignedToUserId: event.target.value ? Number(event.target.value) : undefined }))} className="h-10 w-36 rounded-lg border border-slate-200 bg-white px-3 text-sm text-slate-700" /><label className="flex items-center gap-2 text-xs text-slate-500">Du <input aria-label="Date de début" type="date" value={filters.createdFrom ?? ""} onChange={event => setFilters(current => ({ ...current, createdFrom: event.target.value || undefined }))} className="h-10 rounded-lg border border-slate-200 bg-white px-3 text-sm text-slate-700" /></label><label className="flex items-center gap-2 text-xs text-slate-500">Au <input aria-label="Date de fin" type="date" value={filters.createdTo ?? ""} onChange={event => setFilters(current => ({ ...current, createdTo: event.target.value || undefined }))} className="h-10 rounded-lg border border-slate-200 bg-white px-3 text-sm text-slate-700" /></label><span className="ml-auto text-xs text-slate-400">{items.length} résultat(s)</span></CardContent></Card>
    {incidents.error && <div className="rounded-2xl border border-rose-200 bg-rose-50 px-5 py-4 text-sm text-rose-700"><strong>API unavailable</strong><p className="mt-1">{incidents.error.message}</p></div>}
    <Card className="border-slate-200/80 shadow-sm"><CardHeader><p className="eyebrow">Human response</p><CardTitle className="mt-2">Incident register</CardTitle></CardHeader><CardContent>{incidents.isLoading ? <p className="py-8 text-sm text-slate-500">Chargement des incidents…</p> : incidents.error ? <div className="py-10 text-center"><p className="font-medium text-rose-700">API unavailable</p><p className="mx-auto mt-2 max-w-lg text-sm leading-6 text-rose-600">Les incidents ne peuvent pas être comptés tant que l’API n’est pas disponible.</p></div> : items.length === 0 ? <div className="py-10 text-center"><CheckCircle2 className="mx-auto h-8 w-8 text-emerald-500" /><p className="mt-3 font-medium text-slate-800">No incidents</p><p className="mx-auto mt-2 max-w-lg text-sm leading-6 text-slate-500">Aucun incident ne correspond aux filtres. Les données ne sont jamais remplacées par des incidents fictifs.</p></div> : <div className="space-y-3">{items.map(incident => <Link key={incident.id} href={`/incidents/${incident.id}`} className="block rounded-2xl border border-slate-200 p-4 transition hover:-translate-y-0.5 hover:border-slate-300 hover:shadow-sm"><div className="flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><div><div className="flex flex-wrap items-center gap-2"><span className="font-medium text-slate-900">{formatIncidentCode(incident.id)} · {incident.title}</span><Status value={incident.severity} /><Status value={incident.status} /></div><p className="mt-2 text-sm text-slate-500">Source {incident.source} · {incident.monitoringTargetId ? `Target #${incident.monitoringTargetId}` : "Sans cible"}</p></div><div className="text-right text-xs text-slate-400"><p>{incident.assignedToUserId ? `Assigné à #${incident.assignedToUserId}` : "Non assigné"}</p><p className="mt-1">Créé le {new Date(incident.createdAt).toLocaleString()}</p></div></div></Link>)}</div>}</CardContent></Card>
  </section>;
}
function IncidentDetail({ id }: { id: number }) {
  const { user } = useAuth();
  const incident = trpc.incidents.get.useQuery({ id });
  const utils = trpc.useUtils();
  const transition = trpc.incidents.transition.useMutation({ onSuccess: () => { void incident.refetch(); void utils.incidents.list.invalidate(); } });
  const assign = trpc.incidents.assign.useMutation({ onSuccess: () => { void incident.refetch(); } });
  const data = incident.data;
  if (incident.isLoading) return <div className="py-12 text-sm text-slate-500">Chargement de l’incident…</div>;
  if (incident.error || !data) return <div className="rounded-2xl border border-rose-200 bg-rose-50 px-5 py-4 text-sm text-rose-700"><strong>Incident unavailable</strong><p className="mt-1">{incident.error?.message ?? "Incident not found"}</p><Link href="/incidents" className="mt-4 inline-flex text-sm font-medium underline">Retour aux incidents</Link></div>;
  const item = data.incident;
  const next: Record<string, "ACKNOWLEDGED" | "IN_PROGRESS" | "RESOLVED" | "CLOSED" | undefined> = { OPEN: "ACKNOWLEDGED", ACKNOWLEDGED: "IN_PROGRESS", IN_PROGRESS: "RESOLVED", RESOLVED: "CLOSED" };
  const nextStatus = next[item.status];
  return <section className="space-y-8"><header><Link href="/incidents" className="inline-flex items-center text-sm text-slate-500 hover:text-slate-900"><ArrowLeft className="mr-2 h-4 w-4" />Tous les incidents</Link><div className="mt-6 flex flex-col justify-between gap-5 lg:flex-row lg:items-end"><div><p className="eyebrow">Incident detail</p><h1 className="mt-3 text-4xl font-semibold tracking-[-0.04em] text-slate-950">{formatIncidentCode(item.id)}</h1><p className="mt-2 text-xl font-medium text-slate-800">{item.title}</p></div><div className="flex flex-wrap gap-2"><Status value={item.severity} /><Status value={item.status} /></div></div></header>
    <div className="grid gap-5 lg:grid-cols-[1.5fr_1fr]"><Card className="border-slate-200/80 shadow-sm"><CardHeader><p className="eyebrow">Operational context</p><CardTitle className="mt-2">{item.description || "Aucune description"}</CardTitle></CardHeader><CardContent className="grid gap-4 text-sm text-slate-600 sm:grid-cols-2"><Info label="Source" value={item.source} /><Info label="Target" value={item.monitoringTargetId ? `Monitoring target #${item.monitoringTargetId}` : "Sans cible"} /><Info label="Alert" value={item.alertId ? `Alert #${item.alertId}` : "Incident manuel"} /><Info label="Assignation" value={item.assignedToUserId ? `User #${item.assignedToUserId}` : "Non assigné"} /></CardContent></Card><Card className="border-slate-200/80 shadow-sm"><CardHeader><p className="eyebrow">Lifecycle</p><CardTitle className="mt-2">Actions</CardTitle></CardHeader><CardContent className="space-y-3">{nextStatus ? <Button className="w-full bg-slate-950 hover:bg-slate-800" onClick={() => transition.mutate({ id: item.id, status: nextStatus })} disabled={transition.isPending}>{transition.isPending && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}{nextStatus === "ACKNOWLEDGED" ? "Acquitter" : nextStatus === "IN_PROGRESS" ? "Démarrer l’intervention" : nextStatus === "RESOLVED" ? "Résoudre" : "Fermer"}</Button> : <div className="rounded-xl bg-slate-50 p-3 text-sm text-slate-500"><Lock className="mb-2 h-4 w-4" />Cycle terminé. Un incident CLOSED ne revient pas silencieusement à OPEN.</div>}{transition.error && <p className="text-sm text-rose-600">{transition.error.message}</p>}{item.assignedToUserId === null && <Button variant="outline" className="w-full" onClick={() => user && assign.mutate({ id: item.id, assignedToUserId: user.id })} disabled={assign.isPending || !user}><UserRound className="mr-2 h-4 w-4" />Assigner à l’utilisateur courant</Button>}</CardContent></Card></div>
    <Card className="border-slate-200/80 shadow-sm"><CardHeader><p className="eyebrow">Persisted history</p><CardTitle className="mt-2">Timeline</CardTitle></CardHeader><CardContent>{data.history.length === 0 ? <p className="py-6 text-sm text-slate-500">Aucun événement historique.</p> : <div className="space-y-5">{data.history.map(event => <div key={event.id} className="flex gap-3"><div className="mt-1 grid h-7 w-7 shrink-0 place-items-center rounded-full bg-slate-100"><Clock3 className="h-3.5 w-3.5 text-slate-500" /></div><div><p className="text-sm font-medium text-slate-800">{event.action.replaceAll("_", " ")}</p><p className="mt-1 text-xs text-slate-400">{new Date(event.createdAt).toLocaleString()}{event.actorUserId ? ` · user #${event.actorUserId}` : ""}</p></div></div>)}</div>}</CardContent></Card>
  </section>;
}
function Info({ label, value }: { label: string; value: string }) { return <div className="rounded-xl bg-slate-50 p-3"><p className="text-[10px] font-semibold uppercase tracking-[0.16em] text-slate-400">{label}</p><p className="mt-1 font-medium text-slate-700">{value}</p></div>; }
