import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { trpc } from "@/lib/trpc";
import { Activity, ArrowLeft, CheckCircle2, CircleAlert, Cpu, Database, HardDrive, MemoryStick, Network, Plus, Server, ShieldAlert, WifiOff } from "lucide-react";
import { useMemo, useState } from "react";
import { toast } from "sonner";
import { Link, useLocation, useRoute } from "wouter";

const statusStyles: Record<string, string> = { UP: "border-emerald-200 bg-emerald-50 text-emerald-700", DOWN: "border-rose-200 bg-rose-50 text-rose-700", UNKNOWN: "border-amber-200 bg-amber-50 text-amber-700", NOT_CONFIGURED: "border-slate-200 bg-slate-100 text-slate-500" };
const statusLabels: Record<string, string> = { UP: "UP", DOWN: "DOWN", UNKNOWN: "UNKNOWN", NOT_CONFIGURED: "NOT CONFIGURED" };

function StatusBadge({ status }: { status: string }) { return <Badge variant="outline" className={`gap-1.5 font-semibold ${statusStyles[status] || statusStyles.UNKNOWN}`}><span className="h-1.5 w-1.5 rounded-full bg-current" />{statusLabels[status] || status}</Badge>; }
function PageHeader({ eyebrow, title, description, action }: { eyebrow: string; title: string; description: string; action?: React.ReactNode }) { return <div className="mb-8 flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="eyebrow">{eyebrow}</p><h1 className="mt-3 text-4xl font-semibold tracking-[-0.04em] text-slate-950">{title}</h1><p className="mt-3 max-w-2xl text-sm leading-6 text-slate-500">{description}</p></div>{action}</div>; }
function BackendNotice({ unavailable }: { unavailable: boolean }) { return unavailable ? <div className="mb-6 flex items-start gap-3 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-900"><WifiOff className="mt-0.5 h-5 w-5 shrink-0" /><div><p className="font-semibold">Monitoring backend unavailable</p><p className="mt-1 text-amber-800/80">Prometheus ne répond pas. Aucun zéro ni donnée de substitution n’est affiché.</p></div></div> : null; }

export default function MonitoringPage() {
  const [, setLocation] = useLocation();
  const [targetRoute, targetParams] = useRoute("/monitoring/targets/:id");
  if (targetRoute && targetParams?.id) return <MonitoringTargetDetails id={Number(targetParams.id)} onBack={() => setLocation("/monitoring/targets")} />;
  return <MonitoringOverview />;
}

function MonitoringOverview() {
  const [, setLocation] = useLocation();
  const { data, isLoading, error } = trpc.monitoring.overview.useQuery(undefined, { refetchInterval: 30000 });
  const unavailable = error?.message?.includes("Monitoring backend unavailable") || data?.backendStatus === "UNAVAILABLE";
  const counts = data?.counts ?? { UP: 0, DOWN: 0, UNKNOWN: 0, NOT_CONFIGURED: 0 };
  return <section><PageHeader eyebrow="Control plane / monitoring" title="Monitoring overview" description="L’état observé des cibles configurées par Prometheus. Une cible non configurée n’est jamais assimilée à une machine arrêtée." action={<Button onClick={() => setLocation("/monitoring/targets")} className="bg-slate-950 text-white hover:bg-slate-800"><Server className="mr-2 h-4 w-4" />Gérer les targets</Button>} /><BackendNotice unavailable={Boolean(unavailable)} /><div className="mb-8 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{(["UP", "DOWN", "UNKNOWN", "NOT_CONFIGURED"] as const).map((status, index) => <div key={status} className="surface-card p-5"><div className="flex items-center justify-between"><span className="text-xs font-semibold uppercase tracking-[0.16em] text-slate-400">{statusLabels[status]}</span>{index === 0 ? <CheckCircle2 className="h-5 w-5 text-emerald-500" /> : index === 1 ? <ShieldAlert className="h-5 w-5 text-rose-500" /> : index === 2 ? <CircleAlert className="h-5 w-5 text-amber-500" /> : <Activity className="h-5 w-5 text-slate-400" />}</div><p className="mt-5 text-3xl font-semibold tracking-tight text-slate-950">{isLoading ? "—" : counts[status]}</p><p className="mt-1 text-xs text-slate-400">cible{counts[status] > 1 ? "s" : ""}</p></div>)}</div><div className="surface-card overflow-hidden"><div className="flex items-center justify-between border-b border-slate-100 px-6 py-5"><div><p className="eyebrow">Targets</p><h2 className="mt-2 text-xl font-semibold tracking-tight text-slate-950">Cibles observées</h2></div><span className="rounded-full bg-slate-100 px-3 py-1 text-xs font-semibold text-slate-500">{data?.targets.length ?? 0} configurée{(data?.targets.length ?? 0) > 1 ? "s" : ""}</span></div>{!data?.targets.length && !isLoading ? <EmptyState title="Aucune cible configurée" description="Associez un Asset Linux à un endpoint Node Exporter pour commencer une observation réelle." action={<Button variant="outline" onClick={() => setLocation("/monitoring/targets")}><Plus className="mr-2 h-4 w-4" />Configurer une cible</Button>} /> : <div className="divide-y divide-slate-100">{data?.targets.map(target => <button key={target.id} onClick={() => setLocation(`/monitoring/targets/${target.id}`)} className="flex w-full items-center justify-between gap-4 px-6 py-5 text-left transition hover:bg-slate-50"><div className="flex min-w-0 items-center gap-4"><div className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-blue-50 text-blue-600"><Server className="h-5 w-5" /></div><div className="min-w-0"><p className="truncate font-semibold text-slate-900">{target.endpoint}:{target.port}</p><p className="mt-1 truncate text-xs text-slate-400">Asset #{target.assetId} · {target.type}</p></div></div><StatusBadge status={target.liveStatus} /></button>)}</div>}</div></section>;
}

function MonitoringTargets() {
  const [, setLocation] = useLocation();
  const assetInput = useMemo(() => ({ page: 1, pageSize: 100 }), []);
  const { data: assets } = trpc.infrastructure.assets.list.useQuery(assetInput);
  const { data: targets, isLoading, error } = trpc.monitoring.targets.list.useQuery();
  const utils = trpc.useUtils();
  const create = trpc.monitoring.targets.create.useMutation({ onSuccess: async () => { toast.success("Cible de monitoring créée"); await utils.monitoring.invalidate(); }, onError: error => toast.error(error.message) });
  const [assetId, setAssetId] = useState(""); const [endpoint, setEndpoint] = useState(""); const [port, setPort] = useState("9100"); const [enabled, setEnabled] = useState("false");
  const submit = (event: React.FormEvent) => { event.preventDefault(); if (!assetId || !endpoint) return toast.error("Asset et endpoint sont requis"); create.mutate({ assetId: Number(assetId), type: "NODE_EXPORTER", endpoint, port: Number(port), enabled: enabled === "true" }); };
  return <section><PageHeader eyebrow="Monitoring / targets" title="Monitoring targets" description="Une cible décrit le lien entre un Asset d’inventaire et un exporter. Les séries temporelles restent dans Prometheus, jamais dans PostgreSQL." action={<Button variant="outline" onClick={() => setLocation("/monitoring")}><ArrowLeft className="mr-2 h-4 w-4" />Overview</Button>} /><div className="grid gap-6 xl:grid-cols-[1fr_380px]"><div className="surface-card overflow-hidden"><div className="border-b border-slate-100 px-6 py-5"><p className="eyebrow">Configuration persistée</p><h2 className="mt-2 text-xl font-semibold text-slate-950">Targets Node Exporter</h2></div>{error ? <ErrorState message={error.message} /> : !targets?.length && !isLoading ? <EmptyState title="Aucune target" description="Aucune configuration de monitoring n’est injectée automatiquement." /> : <div className="divide-y divide-slate-100">{targets?.map(target => <Link key={target.id} href={`/monitoring/targets/${target.id}`} className="flex items-center justify-between gap-4 px-6 py-5 transition hover:bg-slate-50"><div><p className="font-semibold text-slate-900">{target.endpoint}:{target.port}</p><p className="mt-1 text-xs text-slate-400">Asset #{target.assetId} · {target.type} · {target.enabled ? "activée" : "désactivée"}</p></div><StatusBadge status={target.status} /></Link>)}</div>}</div><form onSubmit={submit} className="surface-card p-6"><p className="eyebrow">Nouvelle configuration</p><h2 className="mt-2 text-xl font-semibold text-slate-950">Ajouter une target</h2><p className="mt-2 text-sm leading-6 text-slate-500">Seul Node Exporter est réellement implémenté. Les autres types restent PLANNED.</p><div className="mt-6 space-y-4"><div><label className="field-label">Asset parent</label><Select value={assetId} onValueChange={setAssetId}><SelectTrigger><SelectValue placeholder="Choisir un asset" /></SelectTrigger><SelectContent>{assets?.items.map(asset => <SelectItem key={asset.id} value={String(asset.id)}>{asset.assetTag} · {asset.displayName}</SelectItem>)}</SelectContent></Select></div><div><label className="field-label">Endpoint</label><Input value={endpoint} onChange={event => setEndpoint(event.target.value)} placeholder="node-exporter ou 192.0.2.10" /></div><div className="grid grid-cols-2 gap-3"><div><label className="field-label">Port</label><Input value={port} onChange={event => setPort(event.target.value)} inputMode="numeric" /></div><div><label className="field-label">État</label><Select value={enabled} onValueChange={setEnabled}><SelectTrigger><SelectValue /></SelectTrigger><SelectContent><SelectItem value="false">NOT CONFIGURED</SelectItem><SelectItem value="true">CONFIGURED</SelectItem></SelectContent></Select></div></div><Button type="submit" disabled={create.isPending} className="w-full bg-slate-950 text-white hover:bg-slate-800"><Plus className="mr-2 h-4 w-4" />{create.isPending ? "Enregistrement…" : "Enregistrer la target"}</Button></div></form></div></section>;
}

function MonitoringTargetDetails({ id, onBack }: { id: number; onBack: () => void }) {
  const input = useMemo(() => ({ id }), [id]);
  const { data: target, isLoading, error } = trpc.monitoring.targets.get.useQuery(input);
  const { data: observation, isLoading: metricsLoading, error: metricsError } = trpc.monitoring.targets.metrics.useQuery(input, { enabled: Boolean(id), refetchInterval: 30000 });
  if (isLoading) return <div className="py-20 text-center text-sm text-slate-500">Chargement de la target…</div>;
  if (error || !target) return <ErrorState message={error?.message || "Monitoring target not found"} />;
  const unavailable = observation?.backendStatus === "UNAVAILABLE" || metricsError?.message?.includes("Monitoring backend unavailable");
  const metrics = observation?.metrics;
  return <section><PageHeader eyebrow="Monitoring / target details" title={`${target.endpoint}:${target.port}`} description={`Asset #${target.assetId} · ${target.type}. L’état observé est séparé de la configuration persistée.`} action={<Button variant="outline" onClick={onBack}><ArrowLeft className="mr-2 h-4 w-4" />Toutes les targets</Button>} /><BackendNotice unavailable={Boolean(unavailable)} /><div className="mb-6 flex flex-wrap items-center gap-3"><StatusBadge status={observation?.targetStatus || target.status} /><Badge variant="outline" className="border-slate-200 bg-white text-slate-600">{target.enabled ? "CONFIGURED" : "NOT CONFIGURED"}</Badge>{observation?.observedAt && <span className="text-xs text-slate-400">Dernière observation : {new Date(observation.observedAt).toLocaleString()}</span>}</div>{!target.enabled ? <div className="surface-card p-8"><div className="flex items-start gap-4"><Activity className="h-6 w-6 text-slate-400" /><div><h2 className="font-semibold text-slate-900">Monitoring non configuré</h2><p className="mt-2 max-w-xl text-sm leading-6 text-slate-500">Cette target existe dans l’inventaire de monitoring mais n’interroge pas Prometheus tant qu’elle est désactivée. Cela n’indique pas que l’Asset est DOWN.</p></div></div></div> : <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3"><MetricCard icon={Activity} label="Disponibilité" value={metrics?.availability === 1 ? "Accessible" : metrics?.availability === 0 ? "Inaccessible" : metricsLoading ? "Observation…" : "Indisponible"} unit="up" /><MetricCard icon={Cpu} label="CPU" value={formatMetric(metrics?.cpuPercent, metricsLoading)} unit="%" /><MetricCard icon={MemoryStick} label="RAM" value={formatMetric(metrics?.memoryPercent, metricsLoading)} unit="% utilisée" /><MetricCard icon={HardDrive} label="Disque" value={formatMetric(metrics?.diskPercent, metricsLoading)} unit="% utilisé" /><MetricCard icon={Network} label="Réseau entrant" value={formatMetric(metrics?.networkReceiveBytesPerSecond, metricsLoading)} unit="octets/s" /><MetricCard icon={Database} label="Réseau sortant" value={formatMetric(metrics?.networkTransmitBytesPerSecond, metricsLoading)} unit="octets/s" /></div>}</section>;
}

function MetricCard({ icon: Icon, label, value, unit }: { icon: typeof Activity; label: string; value: string; unit: string }) { return <div className="surface-card p-5"><Icon className="h-5 w-5 text-blue-600" /><p className="mt-5 text-xs font-semibold uppercase tracking-[0.16em] text-slate-400">{label}</p><p className="mt-2 text-2xl font-semibold tracking-tight text-slate-950">{value}</p><p className="mt-1 text-xs text-slate-400">{unit}</p></div>; }
function formatMetric(value: number | null | undefined, loading: boolean) { return loading ? "…" : value === null || value === undefined ? "Indisponible" : value.toFixed(1); }
function EmptyState({ title, description, action }: { title: string; description: string; action?: React.ReactNode }) { return <div className="grid min-h-64 place-items-center p-8 text-center"><div><div className="mx-auto grid h-12 w-12 place-items-center rounded-2xl bg-slate-100 text-slate-400"><Activity className="h-5 w-5" /></div><h3 className="mt-4 font-semibold text-slate-800">{title}</h3><p className="mx-auto mt-2 max-w-sm text-sm leading-6 text-slate-500">{description}</p>{action && <div className="mt-5">{action}</div>}</div></div>; }
function ErrorState({ message }: { message: string }) { return <div className="m-6 rounded-2xl border border-rose-200 bg-rose-50 p-5 text-sm text-rose-800"><p className="font-semibold">Erreur de monitoring</p><p className="mt-1">{message}</p></div>; }

export { MonitoringTargets };
