import { describe, expect, it } from "vitest";
import fs from "node:fs";

const schema = fs.readFileSync(new URL("../drizzle/schema.ts", import.meta.url), "utf8");
const migration = fs.readFileSync(new URL("../drizzle-pg/0000_perfect_tyrannus.sql", import.meta.url), "utf8");
const roleSeedMigration = fs.readFileSync(new URL("../drizzle-pg/0001_seed_role_catalog.sql", import.meta.url), "utf8");
const db = fs.readFileSync(new URL("./db.ts", import.meta.url), "utf8");

describe("PostgreSQL migration boundary", () => {
  it("uses PostgreSQL Drizzle primitives and preserves the domain tables", () => {
    expect(schema).toContain('from "drizzle-orm/pg-core"');
    expect(schema).toContain("pgTable(\"users\"");
    expect(schema).toContain("pgTable(\"incidents\"");
    expect(schema).not.toMatch(/mysqlTable|mysqlEnum|mysql-core/);
  });

  it("contains PostgreSQL DDL for enums, identity columns and foreign keys", () => {
    expect(migration).toContain('CREATE TYPE "public"."incident_status" AS ENUM');
    expect(migration).toContain("GENERATED BY DEFAULT AS IDENTITY");
    expect(migration).toContain('REFERENCES "public"."users"');
    expect(migration).not.toMatch(/AUTO_INCREMENT|\bmysql\b|CREATE TABLE `/i);
  });

  it("uses a referenced unique constraint for roles and seeds the OAuth default role", () => {
    expect(schema).toContain('unique("roles_slug_unique").on(table.slug)');
    expect(migration).toContain('CONSTRAINT "roles_slug_unique" UNIQUE("slug")');
    expect(migration).toContain('REFERENCES "public"."roles"("slug")');
    expect(migration).not.toContain('CREATE UNIQUE INDEX "roles_slug_unique"');
    expect(roleSeedMigration).toContain("('user', 'Utilisateur'");
    expect(roleSeedMigration).toContain('ON CONFLICT ("slug") DO UPDATE');
  });

  it("uses node-postgres and rejects incompatible URL schemes in the active DB helper", () => {
    expect(db).toContain('drizzle-orm/node-postgres');
    expect(db).toContain('new Pool({ connectionString: databaseUrl })');
    expect(db).toContain('protocol !== "postgres:"');
    expect(db).toContain('protocol !== "postgresql:"');
    expect(db).not.toContain("insertId");
    expect(db).not.toContain("onDuplicateKeyUpdate");
  });
});
