import { TRPCError } from "@trpc/server";
import { z } from "zod";
import { COOKIE_NAME } from "@shared/const";
import { getSessionCookieOptions } from "./_core/cookies";
import { systemRouter } from "./_core/systemRouter";
import { adminProcedure, identityAdminProcedure, operationsProcedure, publicProcedure, roleProcedure, ROLE_SLUGS, router } from "./_core/trpc";
import { createAuditLog } from "./db";
import { changeUserAccess, listIdentityRoles, listIdentityUsers } from "./services/identity";
import { getRecentAudit, recordAuthEvent, ROLE_CATALOG } from "./services/access";
import { ASSET_STATUSES, ASSET_TYPES, ENVIRONMENTS, RELATIONSHIP_TYPES, createInventoryAsset, createInventoryInstallation, createInventoryInterface, createInventoryLocation, createInventoryNetworkDevice, createInventoryRelationship, createInventorySoftware, inventoryOverview, readAsset, readAssets, readInstallation, readInstallations, readLocation, readLocations, readNetworkDevice, readNetworkInterface, readNetworkInterfaces, readSoftwareItem, readRelationships, readSoftware, removeInventoryAsset, removeInventoryInstallation, removeInventoryInterface, removeInventoryLocation, removeInventoryNetworkDevice, removeInventoryRelationship, removeInventorySoftware, updateInventoryAsset, updateInventoryInstallation, updateInventoryInterface, updateInventoryLocation, updateInventoryNetworkDevice, updateInventoryRelationship, updateInventorySoftware } from "./services/inventory";
import { createConfiguredMonitoringTarget, getConfiguredMonitoringTarget, getMonitoringObservation, getMonitoringOverview, listConfiguredMonitoringTargets, removeConfiguredMonitoringTarget, updateConfiguredMonitoringTarget, MONITORING_TYPES } from "./services/monitoring";

const roleSchema = z.enum([ROLE_SLUGS.ADMIN, ROLE_SLUGS.SYSTEMS_NETWORK_ADMIN, ROLE_SLUGS.TECHNICIAN, ROLE_SLUGS.IT_MANAGER, ROLE_SLUGS.USER]);
const statusSchema = z.enum(["active", "disabled"]);
const assetTypeSchema = z.enum(ASSET_TYPES);
const assetStatusSchema = z.enum(ASSET_STATUSES);
const environmentSchema = z.enum(ENVIRONMENTS);
const assetFields = { assetTag: z.string().min(1).max(128), hostname: z.string().max(255).optional().nullable(), displayName: z.string().min(1).max(255), description: z.string().max(5000).optional().nullable(), serialNumber: z.string().max(255).optional().nullable(), assetType: assetTypeSchema, primaryIp: z.string().max(64).optional().nullable(), primaryMac: z.string().max(32).optional().nullable(), domain: z.string().max(255).optional().nullable(), fqdn: z.string().max(255).optional().nullable(), os: z.string().max(128).optional().nullable(), osDistribution: z.string().max(128).optional().nullable(), osVersion: z.string().max(128).optional().nullable(), architecture: z.string().max(64).optional().nullable(), kernelVersion: z.string().max(128).optional().nullable(), environment: environmentSchema, role: z.string().max(128).optional().nullable(), locationId: z.number().int().positive().optional().nullable(), status: assetStatusSchema, manufacturer: z.string().max(128).optional().nullable(), model: z.string().max(128).optional().nullable(), cpuCores: z.number().int().nonnegative().optional().nullable(), memoryMb: z.number().int().nonnegative().optional().nullable(), storageGb: z.number().int().nonnegative().optional().nullable(), notes: z.string().max(5000).optional().nullable() };
const createAssetSchema = z.object(assetFields);
const updateAssetSchema = z.object(assetFields).partial().refine(value => Object.keys(value).length > 0, "At least one field is required");
const listAssetSchema = z.object({ search: z.string().max(120).optional(), assetType: assetTypeSchema.optional(), status: assetStatusSchema.optional(), environment: environmentSchema.optional(), locationId: z.number().int().positive().optional(), page: z.number().int().min(1).default(1), pageSize: z.number().int().min(1).max(100).default(25) }).optional();
const inventoryManagerProcedure = roleProcedure(ROLE_SLUGS.ADMIN, ROLE_SLUGS.IT_MANAGER, ROLE_SLUGS.SYSTEMS_NETWORK_ADMIN);
const relationTypeSchema = z.enum(RELATIONSHIP_TYPES);
const networkInterfaceFields = { assetId: z.number().int().positive(), name: z.string().min(1).max(128), interfaceType: z.string().max(64).optional().nullable(), macAddress: z.string().max(32).optional().nullable(), ipAddress: z.string().max(64).optional().nullable(), prefix: z.string().max(32).optional().nullable(), vlan: z.number().int().min(1).max(4094).optional().nullable(), speedMbps: z.number().int().nonnegative().optional().nullable(), administrativeState: z.string().max(32).optional().nullable(), operationalState: z.string().max(32).optional().nullable(), description: z.string().max(5000).optional().nullable() };
const softwareFields = { name: z.string().min(1).max(255), vendor: z.string().max(160).optional().nullable(), version: z.string().max(128).optional().nullable(), category: z.string().max(128).optional().nullable(), license: z.string().max(128).optional().nullable(), status: z.string().max(64).default("ACTIVE"), description: z.string().max(5000).optional().nullable() };
const installationFields = { assetId: z.number().int().positive(), softwareId: z.number().int().positive(), installedVersion: z.string().max(128).optional().nullable(), installedAt: z.coerce.date().optional().nullable(), updatedAt: z.coerce.date().optional().nullable(), status: z.string().max(64).default("ACTIVE") };
const locationFields = { name: z.string().min(1).max(160), kind: z.string().min(1).max(64).default("site"), address: z.string().max(5000).optional().nullable(), description: z.string().max(5000).optional().nullable() };
const monitoringTypeSchema = z.enum(MONITORING_TYPES);
const monitoringTargetFields = { assetId: z.number().int().positive(), type: monitoringTypeSchema.default("NODE_EXPORTER"), endpoint: z.string().min(1).max(255), port: z.number().int().min(1).max(65535).default(9100), enabled: z.boolean().default(false), labels: z.record(z.string(), z.string()).optional() };

export const appRouter = router({
  system: systemRouter,
  auth: router({
    me: publicProcedure.query(({ ctx }) => { if (ctx.user) void recordAuthEvent(ctx.user.id, "AUTH_SESSION_CHECK", ctx.req); return ctx.user; }),
    logout: publicProcedure.mutation(({ ctx }) => { if (ctx.user) void recordAuthEvent(ctx.user.id, "AUTH_LOGOUT", ctx.req); const cookieOptions = getSessionCookieOptions(ctx.req); ctx.res.clearCookie(COOKIE_NAME, { ...cookieOptions, maxAge: -1 }); return { success: true } as const; }),
  }),
  users: router({
    list: identityAdminProcedure.input(z.object({ search: z.string().max(120).optional() }).optional()).query(({ input }) => listIdentityUsers(input?.search)),
    roles: identityAdminProcedure.query(async () => listIdentityRoles().then(persisted => persisted.length ? persisted : ROLE_CATALOG)),
    updateAccess: identityAdminProcedure.input(z.object({ userId: z.number().int().positive(), role: roleSchema.optional(), status: statusSchema.optional() }).refine(value => value.role || value.status, "At least one access change is required")).mutation(({ ctx, input }) => changeUserAccess({ actorUserId: ctx.user.id, actorRole: ctx.user.role, userId: input.userId, role: input.role, status: input.status })),
  }),
  audit: router({ recent: adminProcedure.input(z.object({ limit: z.number().int().min(1).max(100).default(50) })).query(({ input }) => getRecentAudit(input.limit)) }),
  infrastructure: router({
    overview: operationsProcedure.query(() => inventoryOverview()),
    assets: router({
      list: operationsProcedure.input(listAssetSchema).query(({ input }) => readAssets(input ?? {})),
      get: operationsProcedure.input(z.object({ id: z.number().int().positive() })).query(({ input }) => readAsset(input.id)),
      create: inventoryManagerProcedure.input(createAssetSchema).mutation(({ ctx, input }) => createInventoryAsset(ctx.user.id, input)),
      update: inventoryManagerProcedure.input(z.object({ id: z.number().int().positive(), data: updateAssetSchema })).mutation(({ ctx, input }) => updateInventoryAsset(ctx.user.id, input.id, input.data)),
      remove: inventoryManagerProcedure.input(z.object({ id: z.number().int().positive() })).mutation(({ ctx, input }) => removeInventoryAsset(ctx.user.id, input.id)),
    }),
    servers: router({ list: operationsProcedure.input(listAssetSchema).query(({ input }) => readAssets({ ...(input ?? {}), assetType: "server" })) }),
    workstations: router({ list: operationsProcedure.input(listAssetSchema).query(({ input }) => readAssets({ ...(input ?? {}), assetType: "workstation" })) }),
    networkDevices: router({ list: operationsProcedure.input(listAssetSchema).query(({ input }) => readAssets({ ...(input ?? {}), assetType: "network_device" })), get: operationsProcedure.input(z.object({ assetId: z.number().int().positive() })).query(({ input }) => readNetworkDevice(input.assetId)), create: inventoryManagerProcedure.input(z.object({ assetId: z.number().int().positive(), deviceType: z.enum(["router", "switch", "firewall", "access_point", "other"]), firmware: z.string().max(128).optional().nullable(), notes: z.string().max(5000).optional().nullable() })).mutation(({ ctx, input }) => createInventoryNetworkDevice(ctx.user.id, input)), update: inventoryManagerProcedure.input(z.object({ assetId: z.number().int().positive(), data: z.object({ deviceType: z.enum(["router", "switch", "firewall", "access_point", "other"]).optional(), firmware: z.string().max(128).optional().nullable(), notes: z.string().max(5000).optional().nullable() }).refine(value => Object.keys(value).length > 0) })).mutation(({ ctx, input }) => updateInventoryNetworkDevice(ctx.user.id, input.assetId, input.data)), remove: inventoryManagerProcedure.input(z.object({ assetId: z.number().int().positive() })).mutation(({ ctx, input }) => removeInventoryNetworkDevice(ctx.user.id, input.assetId)) }),
    networkInterfaces: router({ list: operationsProcedure.input(z.object({ assetId: z.number().int().positive().optional() }).optional()).query(({ input }) => readNetworkInterfaces(input?.assetId)), get: operationsProcedure.input(z.object({ id: z.number().int().positive() })).query(({ input }) => readNetworkInterface(input.id)), create: inventoryManagerProcedure.input(z.object(networkInterfaceFields)).mutation(({ ctx, input }) => createInventoryInterface(ctx.user.id, input)), update: inventoryManagerProcedure.input(z.object({ id: z.number().int().positive(), data: z.object(networkInterfaceFields).partial().refine(value => Object.keys(value).length > 0) })).mutation(({ ctx, input }) => updateInventoryInterface(ctx.user.id, input.id, input.data)), remove: inventoryManagerProcedure.input(z.object({ id: z.number().int().positive() })).mutation(({ ctx, input }) => removeInventoryInterface(ctx.user.id, input.id)) }),
    software: router({ list: operationsProcedure.query(() => readSoftware()), get: operationsProcedure.input(z.object({ id: z.number().int().positive() })).query(({ input }) => readSoftwareItem(input.id)), create: inventoryManagerProcedure.input(z.object(softwareFields)).mutation(({ ctx, input }) => createInventorySoftware(ctx.user.id, input)), update: inventoryManagerProcedure.input(z.object({ id: z.number().int().positive(), data: z.object(softwareFields).partial().refine(value => Object.keys(value).length > 0) })).mutation(({ ctx, input }) => updateInventorySoftware(ctx.user.id, input.id, input.data)), remove: inventoryManagerProcedure.input(z.object({ id: z.number().int().positive() })).mutation(({ ctx, input }) => removeInventorySoftware(ctx.user.id, input.id)) }),
    installations: router({ list: operationsProcedure.input(z.object({ assetId: z.number().int().positive().optional(), softwareId: z.number().int().positive().optional() }).optional()).query(({ input }) => readInstallations(input?.assetId, input?.softwareId)), get: operationsProcedure.input(z.object({ id: z.number().int().positive() })).query(({ input }) => readInstallation(input.id)), create: inventoryManagerProcedure.input(z.object(installationFields)).mutation(({ ctx, input }) => createInventoryInstallation(ctx.user.id, input)), update: inventoryManagerProcedure.input(z.object({ id: z.number().int().positive(), data: z.object(installationFields).partial().refine(value => Object.keys(value).length > 0) })).mutation(({ ctx, input }) => updateInventoryInstallation(ctx.user.id, input.id, input.data)), remove: inventoryManagerProcedure.input(z.object({ id: z.number().int().positive() })).mutation(({ ctx, input }) => removeInventoryInstallation(ctx.user.id, input.id)) }),
    locations: router({ list: operationsProcedure.query(() => readLocations()), get: operationsProcedure.input(z.object({ id: z.number().int().positive() })).query(({ input }) => readLocation(input.id)), create: inventoryManagerProcedure.input(z.object(locationFields)).mutation(({ ctx, input }) => createInventoryLocation(ctx.user.id, input)), update: inventoryManagerProcedure.input(z.object({ id: z.number().int().positive(), data: z.object(locationFields).partial().refine(value => Object.keys(value).length > 0) })).mutation(({ ctx, input }) => updateInventoryLocation(ctx.user.id, input.id, input.data)), remove: inventoryManagerProcedure.input(z.object({ id: z.number().int().positive() })).mutation(({ ctx, input }) => removeInventoryLocation(ctx.user.id, input.id)) }),
    relationships: router({ list: operationsProcedure.input(z.object({ assetId: z.number().int().positive().optional() }).optional()).query(({ input }) => readRelationships(input?.assetId)), create: inventoryManagerProcedure.input(z.object({ sourceAssetId: z.number().int().positive(), destinationAssetId: z.number().int().positive(), relationshipType: relationTypeSchema, sourceInterfaceId: z.number().int().positive().optional().nullable(), destinationInterfaceId: z.number().int().positive().optional().nullable(), description: z.string().max(5000).optional().nullable() })).mutation(({ ctx, input }) => createInventoryRelationship(ctx.user.id, input)), update: inventoryManagerProcedure.input(z.object({ id: z.number().int().positive(), data: z.object({ sourceAssetId: z.number().int().positive().optional(), destinationAssetId: z.number().int().positive().optional(), relationshipType: relationTypeSchema.optional(), sourceInterfaceId: z.number().int().positive().optional().nullable(), destinationInterfaceId: z.number().int().positive().optional().nullable(), description: z.string().max(5000).optional().nullable() }).refine(value => Object.keys(value).length > 0) })).mutation(({ ctx, input }) => updateInventoryRelationship(ctx.user.id, input.id, input.data)), remove: inventoryManagerProcedure.input(z.object({ id: z.number().int().positive() })).mutation(({ ctx, input }) => removeInventoryRelationship(ctx.user.id, input.id)) }),
  }),
  monitoring: router({
    overview: operationsProcedure.query(() => getMonitoringOverview()),
    targets: router({
      list: operationsProcedure.query(() => listConfiguredMonitoringTargets()),
      get: operationsProcedure.input(z.object({ id: z.number().int().positive() })).query(({ input }) => getConfiguredMonitoringTarget(input.id)),
      create: inventoryManagerProcedure.input(z.object(monitoringTargetFields)).mutation(({ ctx, input }) => createConfiguredMonitoringTarget(ctx.user.id, input)),
      update: inventoryManagerProcedure.input(z.object({ id: z.number().int().positive(), data: z.object(monitoringTargetFields).partial() })).mutation(({ ctx, input }) => updateConfiguredMonitoringTarget(ctx.user.id, input.id, input.data)),
      remove: inventoryManagerProcedure.input(z.object({ id: z.number().int().positive() })).mutation(({ ctx, input }) => removeConfiguredMonitoringTarget(ctx.user.id, input.id)),
      status: operationsProcedure.input(z.object({ id: z.number().int().positive() })).query(async ({ input }) => { const observation = await getMonitoringObservation(input.id); return { target: observation.target, backendStatus: observation.backendStatus, targetStatus: observation.targetStatus, observedAt: observation.observedAt, error: observation.error }; }),
      metrics: operationsProcedure.input(z.object({ id: z.number().int().positive() })).query(({ input }) => getMonitoringObservation(input.id)),
    }),
  }),
});
export type AppRouter = typeof appRouter;
