CREATE TYPE "public"."alert_severity" AS ENUM('INFO', 'WARNING', 'CRITICAL');--> statement-breakpoint
CREATE TYPE "public"."alert_status" AS ENUM('PENDING', 'FIRING', 'RESOLVED', 'UNKNOWN');--> statement-breakpoint
CREATE TYPE "public"."asset_status" AS ENUM('ACTIVE', 'INACTIVE', 'MAINTENANCE', 'RETIRED', 'UNKNOWN');--> statement-breakpoint
CREATE TYPE "public"."asset_type" AS ENUM('server', 'workstation', 'network_device');--> statement-breakpoint
CREATE TYPE "public"."environment" AS ENUM('PRODUCTION', 'DEVELOPMENT', 'TEST', 'LAB', 'OTHER');--> statement-breakpoint
CREATE TYPE "public"."incident_status" AS ENUM('OPEN', 'ACKNOWLEDGED', 'IN_PROGRESS', 'RESOLVED', 'CLOSED');--> statement-breakpoint
CREATE TYPE "public"."monitoring_status" AS ENUM('NOT_CONFIGURED', 'CONFIGURED', 'UP', 'DOWN', 'UNKNOWN');--> statement-breakpoint
CREATE TYPE "public"."monitoring_type" AS ENUM('NODE_EXPORTER', 'WINDOWS_EXPORTER', 'SNMP', 'DOCKER', 'PROXMOX', 'CUSTOM');--> statement-breakpoint
CREATE TYPE "public"."user_status" AS ENUM('active', 'disabled');--> statement-breakpoint
CREATE TABLE "alert_rules" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "alert_rules_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(160) NOT NULL,
	"description" text,
	"expression" text NOT NULL,
	"severity" "alert_severity" DEFAULT 'WARNING' NOT NULL,
	"forDurationSeconds" integer DEFAULT 300 NOT NULL,
	"enabled" integer DEFAULT 1 NOT NULL,
	"labels" text,
	"annotations" text,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "alerts" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "alerts_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"ruleId" integer NOT NULL,
	"monitoringTargetId" integer,
	"fingerprint" varchar(128) NOT NULL,
	"severity" "alert_severity" NOT NULL,
	"status" "alert_status" DEFAULT 'PENDING' NOT NULL,
	"summary" varchar(255) NOT NULL,
	"description" text,
	"startedAt" timestamp,
	"resolvedAt" timestamp,
	"lastSeenAt" timestamp DEFAULT now() NOT NULL,
	"labels" text,
	"annotations" text,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "asset_relationships" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "asset_relationships_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"sourceAssetId" integer NOT NULL,
	"destinationAssetId" integer NOT NULL,
	"relationshipType" varchar(64) NOT NULL,
	"sourceInterfaceId" integer,
	"destinationInterfaceId" integer,
	"description" text,
	"createdAt" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "assets" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "assets_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"assetTag" varchar(128) NOT NULL,
	"hostname" varchar(255),
	"displayName" varchar(255) NOT NULL,
	"description" text,
	"serialNumber" varchar(255),
	"assetType" "asset_type" NOT NULL,
	"primaryIp" varchar(64),
	"primaryMac" varchar(32),
	"domain" varchar(255),
	"fqdn" varchar(255),
	"os" varchar(128),
	"osDistribution" varchar(128),
	"osVersion" varchar(128),
	"architecture" varchar(64),
	"kernelVersion" varchar(128),
	"environment" "environment" DEFAULT 'OTHER' NOT NULL,
	"role" varchar(128),
	"locationId" integer,
	"status" "asset_status" DEFAULT 'UNKNOWN' NOT NULL,
	"manufacturer" varchar(128),
	"model" varchar(128),
	"cpuCores" integer,
	"memoryMb" integer,
	"storageGb" integer,
	"notes" text,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "audit_logs" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "audit_logs_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"actorUserId" integer,
	"action" varchar(128) NOT NULL,
	"targetType" varchar(64),
	"targetId" varchar(128),
	"metadata" text,
	"ipAddress" varchar(64),
	"userAgent" text,
	"createdAt" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "incident_history" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "incident_history_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"incidentId" integer NOT NULL,
	"actorUserId" integer,
	"action" varchar(64) NOT NULL,
	"fromStatus" "incident_status",
	"toStatus" "incident_status",
	"metadata" text,
	"createdAt" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "incidents" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "incidents_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"title" varchar(255) NOT NULL,
	"description" text,
	"severity" "alert_severity" DEFAULT 'WARNING' NOT NULL,
	"status" "incident_status" DEFAULT 'OPEN' NOT NULL,
	"source" varchar(64) DEFAULT 'ALERT' NOT NULL,
	"monitoringTargetId" integer,
	"alertId" integer,
	"assignedToUserId" integer,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"acknowledgedAt" timestamp,
	"resolvedAt" timestamp,
	"resolutionNotes" text,
	"updatedAt" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "locations" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "locations_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(160) NOT NULL,
	"kind" varchar(64) DEFAULT 'site' NOT NULL,
	"address" text,
	"description" text,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "monitoring_targets" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "monitoring_targets_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"assetId" integer NOT NULL,
	"type" "monitoring_type" DEFAULT 'NODE_EXPORTER' NOT NULL,
	"endpoint" varchar(255) NOT NULL,
	"port" integer DEFAULT 9100 NOT NULL,
	"enabled" integer DEFAULT 0 NOT NULL,
	"status" "monitoring_status" DEFAULT 'NOT_CONFIGURED' NOT NULL,
	"labels" text,
	"lastObservedAt" timestamp,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "network_devices" (
	"assetId" integer PRIMARY KEY NOT NULL,
	"deviceType" varchar(128) NOT NULL,
	"firmware" varchar(128),
	"notes" text
);
--> statement-breakpoint
CREATE TABLE "network_interfaces" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "network_interfaces_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"assetId" integer NOT NULL,
	"name" varchar(128) NOT NULL,
	"interfaceType" varchar(64),
	"macAddress" varchar(32),
	"ipAddress" varchar(64),
	"prefix" varchar(32),
	"vlan" integer,
	"speedMbps" integer,
	"administrativeState" varchar(32),
	"operationalState" varchar(32),
	"description" text
);
--> statement-breakpoint
CREATE TABLE "permissions" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "permissions_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"slug" varchar(128) NOT NULL,
	"name" varchar(128) NOT NULL,
	"description" text
);
--> statement-breakpoint
CREATE TABLE "role_permissions" (
	"roleId" integer NOT NULL,
	"permissionId" integer NOT NULL
);
--> statement-breakpoint
CREATE TABLE "roles" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "roles_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"slug" varchar(64) NOT NULL,
	"name" varchar(128) NOT NULL,
	"description" text,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "roles_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE "servers" (
	"assetId" integer PRIMARY KEY NOT NULL,
	"serverType" varchar(128),
	"notes" text
);
--> statement-breakpoint
CREATE TABLE "software" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "software_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"name" varchar(255) NOT NULL,
	"vendor" varchar(160),
	"version" varchar(128),
	"category" varchar(128),
	"license" varchar(128),
	"status" varchar(64) DEFAULT 'ACTIVE' NOT NULL,
	"description" text,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "software_installations" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "software_installations_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"assetId" integer NOT NULL,
	"softwareId" integer NOT NULL,
	"installedVersion" varchar(128),
	"installedAt" timestamp,
	"updatedAt" timestamp,
	"status" varchar(64) DEFAULT 'ACTIVE' NOT NULL
);
--> statement-breakpoint
CREATE TABLE "users" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "users_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"openId" varchar(128) NOT NULL,
	"name" varchar(255),
	"email" varchar(320),
	"loginMethod" varchar(64),
	"role" varchar(64) DEFAULT 'user' NOT NULL,
	"status" "user_status" DEFAULT 'active' NOT NULL,
	"createdAt" timestamp DEFAULT now() NOT NULL,
	"updatedAt" timestamp DEFAULT now() NOT NULL,
	"lastSignedIn" timestamp DEFAULT now() NOT NULL,
	"disabledAt" timestamp,
	CONSTRAINT "users_openId_unique" UNIQUE("openId")
);
--> statement-breakpoint
CREATE TABLE "workstations" (
	"assetId" integer PRIMARY KEY NOT NULL,
	"primaryUserId" integer,
	"purchaseDate" timestamp,
	"warrantyUntil" timestamp,
	"notes" text
);
--> statement-breakpoint
ALTER TABLE "alerts" ADD CONSTRAINT "alerts_rule_fk" FOREIGN KEY ("ruleId") REFERENCES "public"."alert_rules"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "alerts" ADD CONSTRAINT "alerts_target_fk" FOREIGN KEY ("monitoringTargetId") REFERENCES "public"."monitoring_targets"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "asset_relationships" ADD CONSTRAINT "asset_relationship_source_fk" FOREIGN KEY ("sourceAssetId") REFERENCES "public"."assets"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "asset_relationships" ADD CONSTRAINT "asset_relationship_destination_fk" FOREIGN KEY ("destinationAssetId") REFERENCES "public"."assets"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "asset_relationships" ADD CONSTRAINT "asset_relationship_source_interface_fk" FOREIGN KEY ("sourceInterfaceId") REFERENCES "public"."network_interfaces"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "asset_relationships" ADD CONSTRAINT "asset_relationship_destination_interface_fk" FOREIGN KEY ("destinationInterfaceId") REFERENCES "public"."network_interfaces"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "assets" ADD CONSTRAINT "assets_location_fk" FOREIGN KEY ("locationId") REFERENCES "public"."locations"("id") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "audit_logs" ADD CONSTRAINT "audit_logs_actor_fk" FOREIGN KEY ("actorUserId") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "incident_history" ADD CONSTRAINT "incident_history_incident_fk" FOREIGN KEY ("incidentId") REFERENCES "public"."incidents"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "incident_history" ADD CONSTRAINT "incident_history_actor_fk" FOREIGN KEY ("actorUserId") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "incidents" ADD CONSTRAINT "incidents_target_fk" FOREIGN KEY ("monitoringTargetId") REFERENCES "public"."monitoring_targets"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "incidents" ADD CONSTRAINT "incidents_alert_fk" FOREIGN KEY ("alertId") REFERENCES "public"."alerts"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "incidents" ADD CONSTRAINT "incidents_assignee_fk" FOREIGN KEY ("assignedToUserId") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "monitoring_targets" ADD CONSTRAINT "monitoring_targets_asset_fk" FOREIGN KEY ("assetId") REFERENCES "public"."assets"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "network_devices" ADD CONSTRAINT "network_devices_asset_fk" FOREIGN KEY ("assetId") REFERENCES "public"."assets"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "network_interfaces" ADD CONSTRAINT "network_interfaces_asset_fk" FOREIGN KEY ("assetId") REFERENCES "public"."assets"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "role_permissions" ADD CONSTRAINT "role_permissions_role_fk" FOREIGN KEY ("roleId") REFERENCES "public"."roles"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "role_permissions" ADD CONSTRAINT "role_permissions_permission_fk" FOREIGN KEY ("permissionId") REFERENCES "public"."permissions"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "servers" ADD CONSTRAINT "servers_asset_fk" FOREIGN KEY ("assetId") REFERENCES "public"."assets"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "software_installations" ADD CONSTRAINT "software_install_asset_fk" FOREIGN KEY ("assetId") REFERENCES "public"."assets"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "software_installations" ADD CONSTRAINT "software_install_software_fk" FOREIGN KEY ("softwareId") REFERENCES "public"."software"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "users" ADD CONSTRAINT "users_role_fk" FOREIGN KEY ("role") REFERENCES "public"."roles"("slug") ON DELETE restrict ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "workstations" ADD CONSTRAINT "workstations_asset_fk" FOREIGN KEY ("assetId") REFERENCES "public"."assets"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "workstations" ADD CONSTRAINT "workstations_user_fk" FOREIGN KEY ("primaryUserId") REFERENCES "public"."users"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
CREATE UNIQUE INDEX "alert_rules_name_unique" ON "alert_rules" USING btree ("name");--> statement-breakpoint
CREATE INDEX "alert_rules_enabled_idx" ON "alert_rules" USING btree ("enabled");--> statement-breakpoint
CREATE INDEX "alert_rules_severity_idx" ON "alert_rules" USING btree ("severity");--> statement-breakpoint
CREATE UNIQUE INDEX "alerts_fingerprint_unique" ON "alerts" USING btree ("fingerprint");--> statement-breakpoint
CREATE INDEX "alerts_rule_idx" ON "alerts" USING btree ("ruleId");--> statement-breakpoint
CREATE INDEX "alerts_target_idx" ON "alerts" USING btree ("monitoringTargetId");--> statement-breakpoint
CREATE INDEX "alerts_status_idx" ON "alerts" USING btree ("status");--> statement-breakpoint
CREATE UNIQUE INDEX "asset_relationship_unique" ON "asset_relationships" USING btree ("sourceAssetId","destinationAssetId","relationshipType");--> statement-breakpoint
CREATE INDEX "asset_relationship_source_idx" ON "asset_relationships" USING btree ("sourceAssetId");--> statement-breakpoint
CREATE INDEX "asset_relationship_destination_idx" ON "asset_relationships" USING btree ("destinationAssetId");--> statement-breakpoint
CREATE UNIQUE INDEX "assets_asset_tag_unique" ON "assets" USING btree ("assetTag");--> statement-breakpoint
CREATE INDEX "assets_hostname_idx" ON "assets" USING btree ("hostname");--> statement-breakpoint
CREATE INDEX "assets_serial_idx" ON "assets" USING btree ("serialNumber");--> statement-breakpoint
CREATE INDEX "assets_type_idx" ON "assets" USING btree ("assetType");--> statement-breakpoint
CREATE INDEX "assets_status_idx" ON "assets" USING btree ("status");--> statement-breakpoint
CREATE INDEX "assets_environment_idx" ON "assets" USING btree ("environment");--> statement-breakpoint
CREATE INDEX "assets_location_idx" ON "assets" USING btree ("locationId");--> statement-breakpoint
CREATE INDEX "audit_logs_actor_idx" ON "audit_logs" USING btree ("actorUserId");--> statement-breakpoint
CREATE INDEX "audit_logs_action_idx" ON "audit_logs" USING btree ("action");--> statement-breakpoint
CREATE INDEX "incident_history_incident_idx" ON "incident_history" USING btree ("incidentId");--> statement-breakpoint
CREATE INDEX "incident_history_created_idx" ON "incident_history" USING btree ("createdAt");--> statement-breakpoint
CREATE INDEX "incidents_status_idx" ON "incidents" USING btree ("status");--> statement-breakpoint
CREATE INDEX "incidents_severity_idx" ON "incidents" USING btree ("severity");--> statement-breakpoint
CREATE INDEX "incidents_target_idx" ON "incidents" USING btree ("monitoringTargetId");--> statement-breakpoint
CREATE INDEX "incidents_assignee_idx" ON "incidents" USING btree ("assignedToUserId");--> statement-breakpoint
CREATE INDEX "incidents_alert_idx" ON "incidents" USING btree ("alertId");--> statement-breakpoint
CREATE UNIQUE INDEX "locations_name_unique" ON "locations" USING btree ("name");--> statement-breakpoint
CREATE INDEX "locations_kind_idx" ON "locations" USING btree ("kind");--> statement-breakpoint
CREATE UNIQUE INDEX "monitoring_targets_asset_type_endpoint_unique" ON "monitoring_targets" USING btree ("assetId","type","endpoint","port");--> statement-breakpoint
CREATE INDEX "monitoring_targets_asset_idx" ON "monitoring_targets" USING btree ("assetId");--> statement-breakpoint
CREATE INDEX "monitoring_targets_status_idx" ON "monitoring_targets" USING btree ("status");--> statement-breakpoint
CREATE INDEX "monitoring_targets_enabled_idx" ON "monitoring_targets" USING btree ("enabled");--> statement-breakpoint
CREATE UNIQUE INDEX "network_interfaces_asset_name_unique" ON "network_interfaces" USING btree ("assetId","name");--> statement-breakpoint
CREATE INDEX "network_interfaces_asset_idx" ON "network_interfaces" USING btree ("assetId");--> statement-breakpoint
CREATE INDEX "network_interfaces_ip_idx" ON "network_interfaces" USING btree ("ipAddress");--> statement-breakpoint
CREATE UNIQUE INDEX "permissions_slug_unique" ON "permissions" USING btree ("slug");--> statement-breakpoint
CREATE UNIQUE INDEX "role_permissions_unique" ON "role_permissions" USING btree ("roleId","permissionId");--> statement-breakpoint
CREATE UNIQUE INDEX "software_name_version_unique" ON "software" USING btree ("name","version");--> statement-breakpoint
CREATE INDEX "software_name_idx" ON "software" USING btree ("name");--> statement-breakpoint
CREATE UNIQUE INDEX "software_install_asset_unique" ON "software_installations" USING btree ("assetId","softwareId");--> statement-breakpoint
CREATE INDEX "software_install_asset_idx" ON "software_installations" USING btree ("assetId");--> statement-breakpoint
CREATE INDEX "software_install_software_idx" ON "software_installations" USING btree ("softwareId");--> statement-breakpoint
CREATE INDEX "users_email_idx" ON "users" USING btree ("email");--> statement-breakpoint
CREATE INDEX "users_role_idx" ON "users" USING btree ("role");--> statement-breakpoint
CREATE INDEX "users_status_idx" ON "users" USING btree ("status");--> statement-breakpoint
CREATE INDEX "workstations_user_idx" ON "workstations" USING btree ("primaryUserId");
