import { createHash } from "node:crypto";
import { TRPCError } from "@trpc/server";
import { createAlert, createAlertRule, createAuditLog, getAlertById, createIncident, createIncidentHistory, getAlertByFingerprint, getAlertRuleById, getAlertRuleByName, getIncidentById, getMonitoringTargetById, getUserById, listAlertRules, listAlerts, listIncidentHistory, listIncidents, updateAlert, updateAlertRule, updateIncident, deleteAlertRule } from "../db";
import { prometheusQuery, MonitoringBackendError } from "./monitoring";
import type { Alert, AlertRule, Incident, InsertAlertRule } from "../../drizzle/schema";

export const ALERT_SEVERITIES = ["INFO", "WARNING", "CRITICAL"] as const;
export const ALERT_STATUSES = ["PENDING", "FIRING", "RESOLVED", "UNKNOWN"] as const;
export const INCIDENT_STATUSES = ["OPEN", "ACKNOWLEDGED", "IN_PROGRESS", "RESOLVED", "CLOSED"] as const;
export type AlertSeverity = typeof ALERT_SEVERITIES[number];
export type AlertStatus = typeof ALERT_STATUSES[number];
export type IncidentStatus = typeof INCIDENT_STATUSES[number];

const initialRuleExpressions = {
  cpu: "100 - (avg by(instance) (rate(node_cpu_seconds_total{mode=\"idle\"}[5m])) * 100) > 90",
  memory: "(1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100 > 85",
  disk: "(1 - (sum(node_filesystem_avail_bytes{fstype!~\"tmpfs|overlay\"}) / sum(node_filesystem_size_bytes{fstype!~\"tmpfs|overlay\"}))) * 100 > 85",
  targetDown: "up == 0",
} as const;

export function fingerprintFor(ruleId: number, targetId: number | null, labels: Record<string, string> = {}) { return createHash("sha256").update(JSON.stringify({ ruleId, targetId, labels: Object.fromEntries(Object.entries(labels).sort()) })).digest("hex"); }
function fail(message: string): never { throw new TRPCError({ code: "BAD_REQUEST", message }); }
function id(value: number) { if (!Number.isInteger(value) || value < 1) fail("Invalid identifier"); return value; }
function json(value?: Record<string, string> | null) { return value ? JSON.stringify(value) : null; }
function parseJson(value?: string | null): Record<string, string> { if (!value) return {}; try { const parsed = JSON.parse(value); return parsed && typeof parsed === "object" && !Array.isArray(parsed) ? parsed : {}; } catch { return {}; } }
export function validateAlertExpression(expression: string) { const value = expression.trim(); if (!value || value.length > 4000 || /[;\u0000]/.test(value) || /\/\//.test(value)) fail("Expression is invalid or contains unsupported syntax"); const pairs: Record<string, string> = { "(": ")", "{": "}", "[": "]" }; const stack: string[] = []; for (const char of value) { if (pairs[char]) stack.push(pairs[char]); else if (Object.values(pairs).includes(char) && stack.pop() !== char) fail("Expression delimiters are unbalanced"); } if (stack.length) fail("Expression delimiters are unbalanced"); return value; }
function ruleInput(input: { name: string; description?: string | null; expression: string; severity: AlertSeverity; forDurationSeconds?: number; enabled?: boolean; labels?: Record<string, string>; annotations?: Record<string, string> }): InsertAlertRule { if (!input.name.trim() || input.name.length > 160) fail("Rule name is invalid"); if (!Number.isInteger(input.forDurationSeconds ?? 300) || (input.forDurationSeconds ?? 300) < 0 || (input.forDurationSeconds ?? 300) > 86400) fail("Rule duration is invalid"); return { name: input.name.trim(), description: input.description ?? null, expression: validateAlertExpression(input.expression), severity: input.severity, forDurationSeconds: input.forDurationSeconds ?? 300, enabled: input.enabled === false ? 0 : 1, labels: json(input.labels), annotations: json(input.annotations) }; }
async function audit(actorUserId: number, action: string, targetType: string, targetId: number, metadata: Record<string, unknown>) { await createAuditLog({ actorUserId, action, targetType, targetId: String(targetId), metadata }); }

export async function listConfiguredAlertRules() { return listAlertRules(); }
export async function getConfiguredAlertRule(ruleId: number) { const rule = await getAlertRuleById(id(ruleId)); if (!rule) throw new TRPCError({ code: "NOT_FOUND", message: "Alert rule not found" }); return rule; }
export async function createConfiguredAlertRule(actorUserId: number, input: Parameters<typeof ruleInput>[0]) { const values = ruleInput(input); const rule = await createAlertRule(values); if (!rule) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Alert rule could not be created" }); await audit(actorUserId, "ALERT_RULE_CREATED", "alert_rule", rule.id, { name: rule.name, severity: rule.severity, enabled: rule.enabled === 1 }); return rule; }
export async function updateConfiguredAlertRule(actorUserId: number, ruleId: number, input: Partial<Parameters<typeof ruleInput>[0]>) { const existing = await getConfiguredAlertRule(ruleId); const values = ruleInput({ name: input.name ?? existing.name, description: input.description ?? existing.description, expression: input.expression ?? existing.expression, severity: input.severity ?? existing.severity, forDurationSeconds: input.forDurationSeconds ?? existing.forDurationSeconds, enabled: input.enabled ?? existing.enabled === 1, labels: input.labels ?? parseJson(existing.labels), annotations: input.annotations ?? parseJson(existing.annotations) }); const rule = await updateAlertRule(existing.id, values); if (!rule) throw new TRPCError({ code: "NOT_FOUND", message: "Alert rule not found" }); const enabledChanged = existing.enabled !== rule.enabled; await audit(actorUserId, enabledChanged ? (rule.enabled === 1 ? "ALERT_RULE_ENABLED" : "ALERT_RULE_DISABLED") : "ALERT_RULE_UPDATED", "alert_rule", rule.id, { name: rule.name, severity: rule.severity, enabled: rule.enabled === 1 }); return rule; }
export async function removeConfiguredAlertRule(actorUserId: number, ruleId: number) { const rule = await getConfiguredAlertRule(ruleId); await deleteAlertRule(rule.id); await audit(actorUserId, "ALERT_RULE_DELETED", "alert_rule", rule.id, { name: rule.name }); return { success: true }; }
export async function ensureInitialAlertRules(actorUserId: number) { const created: AlertRule[] = []; for (const definition of getInitialAlertRuleDefinitions()) { if (await getAlertRuleByName(definition.name)) continue; const rule = await createConfiguredAlertRule(actorUserId, definition); created.push(rule as AlertRule); } return created; }
export function getInitialAlertRuleDefinitions(): Array<{ name: string; description: string; expression: string; severity: AlertSeverity; forDurationSeconds: number; labels: Record<string, string>; annotations: Record<string, string> }> { return [
  { name: "Node CPU high", description: "CPU usage above 90% for five minutes", expression: initialRuleExpressions.cpu, severity: "WARNING" as const, forDurationSeconds: 300, labels: { source: "node-exporter" }, annotations: { summary: "CPU usage is high" } },
  { name: "Node memory pressure", description: "Memory usage above 85%", expression: initialRuleExpressions.memory, severity: "WARNING" as const, forDurationSeconds: 300, labels: { source: "node-exporter" }, annotations: { summary: "Memory pressure detected" } },
  { name: "Node filesystem pressure", description: "Filesystem usage above 85%", expression: initialRuleExpressions.disk, severity: "CRITICAL" as const, forDurationSeconds: 300, labels: { source: "node-exporter", create_incident: "true" }, annotations: { summary: "Filesystem usage is high" } },
  { name: "Monitoring target down", description: "Prometheus reports an unavailable target", expression: initialRuleExpressions.targetDown, severity: "CRITICAL" as const, forDurationSeconds: 60, labels: { source: "prometheus", create_incident: "true" }, annotations: { summary: "Monitoring target is down" } },
]; }

export async function listObservedAlerts(filters: { status?: AlertStatus; severity?: AlertSeverity; monitoringTargetId?: number } = {}) { return listAlerts(filters); }
export async function getObservedAlert(alertId: number) { const alert = await getAlertById(id(alertId)); if (!alert) throw new TRPCError({ code: "NOT_FOUND", message: "Alert not found" }); return alert; }
export async function evaluateAlertRule(rule: AlertRule, monitoringTargetId: number | null, labels: Record<string, string> = {}) {
  if (rule.enabled !== 1) return { status: "UNKNOWN" as const, backendStatus: "NOT_REQUIRED" as const, value: null, fingerprint: fingerprintFor(rule.id, monitoringTargetId, labels) };
  const fingerprint = fingerprintFor(rule.id, monitoringTargetId, labels);
  try { const value = await prometheusQuery(rule.expression); return { status: value === null ? "RESOLVED" as const : value > 0 ? "FIRING" as const : "PENDING" as const, backendStatus: "AVAILABLE" as const, value, fingerprint }; }
  catch (error) { if (error instanceof MonitoringBackendError) return { status: "UNKNOWN" as const, backendStatus: "UNAVAILABLE" as const, value: null, fingerprint }; throw error; }
}
export async function syncAlertObservation(actorUserId: number, ruleId: number, monitoringTargetId: number | null, labels: Record<string, string> = {}) {
  if (monitoringTargetId !== null && !await getMonitoringTargetById(id(monitoringTargetId))) throw new TRPCError({ code: "NOT_FOUND", message: "Monitoring target not found" });
  const rule = await getConfiguredAlertRule(ruleId); const result = await evaluateAlertRule(rule, monitoringTargetId, labels); const existing = await getAlertByFingerprint(result.fingerprint); const now = new Date();
  if (result.status === "UNKNOWN") return { alert: existing ?? null, ...result };
  if (existing) { const updated = await updateAlert(existing.id, { status: result.status, resolvedAt: result.status === "RESOLVED" ? now : null, lastSeenAt: now, updatedAt: now }); return { alert: updated, ...result }; }
  if (result.status === "RESOLVED") return { alert: null, ...result };
  const created = await createAlert({ ruleId: rule.id, monitoringTargetId, fingerprint: result.fingerprint, severity: rule.severity, status: result.status, summary: parseJson(rule.annotations).summary ?? rule.name, description: rule.description, startedAt: now, lastSeenAt: now, labels: json({ ...parseJson(rule.labels), ...labels }), annotations: rule.annotations });
  if (!created) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Alert could not be created" }); await audit(actorUserId, "ALERT_CREATED", "alert", created.id, { ruleId: rule.id, monitoringTargetId, severity: created.severity, status: created.status });
  if (created.status === "FIRING" && created.severity === "CRITICAL" && parseJson(rule.labels).create_incident === "true") await correlateAlertToIncident(actorUserId, created as Alert);
  return { alert: created, ...result };
}

export async function listOpenIncidents(filters: { status?: IncidentStatus; severity?: AlertSeverity; assignedToUserId?: number; monitoringTargetId?: number; createdFrom?: Date; createdTo?: Date } = {}) { return listIncidents(filters); }
export async function getIncidentDetails(incidentId: number) { const incident = await getIncidentById(id(incidentId)); if (!incident) throw new TRPCError({ code: "NOT_FOUND", message: "Incident not found" }); return { incident, history: await listIncidentHistory(incident.id) }; }
export async function createManualIncident(actorUserId: number, input: { title: string; description?: string | null; severity: AlertSeverity; monitoringTargetId?: number | null; alertId?: number | null }) { if (!input.title.trim() || input.title.length > 255) fail("Incident title is invalid"); if (input.monitoringTargetId && !await getMonitoringTargetById(id(input.monitoringTargetId))) throw new TRPCError({ code: "NOT_FOUND", message: "Monitoring target not found" }); if (input.alertId && !await getAlertById(id(input.alertId))) throw new TRPCError({ code: "NOT_FOUND", message: "Alert not found" }); const incident = await createIncident({ title: input.title.trim(), description: input.description ?? null, severity: input.severity, status: "OPEN", source: "MANUAL", monitoringTargetId: input.monitoringTargetId ?? null, alertId: input.alertId ?? null, assignedToUserId: null }); if (!incident) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Incident could not be created" }); await recordIncidentEvent(actorUserId, incident.id, "INCIDENT_CREATED", null, "OPEN", {}); return incident; }
async function correlateAlertToIncident(actorUserId: number, alert: Alert) { const incidentsForAlert = await listIncidents({}); if (incidentsForAlert.some(item => item.alertId === alert.id || (item.monitoringTargetId === alert.monitoringTargetId && item.status !== "CLOSED" && item.status !== "RESOLVED"))) return; const incident = await createIncident({ title: alert.summary, description: alert.description, severity: alert.severity, status: "OPEN", source: "ALERT", monitoringTargetId: alert.monitoringTargetId, alertId: alert.id, assignedToUserId: null }); if (incident) await recordIncidentEvent(actorUserId, incident.id, "INCIDENT_CREATED_FROM_ALERT", null, "OPEN", { alertId: alert.id, fingerprint: alert.fingerprint }); }
async function recordIncidentEvent(actorUserId: number, incidentId: number, action: string, fromStatus: IncidentStatus | null, toStatus: IncidentStatus | null, metadata: Record<string, unknown>) { await createIncidentHistory({ incidentId, actorUserId, action, fromStatus, toStatus, metadata: JSON.stringify(metadata) }); await audit(actorUserId, action, "incident", incidentId, metadata); }
const transitions: Record<IncidentStatus, IncidentStatus[]> = { OPEN: ["ACKNOWLEDGED", "IN_PROGRESS", "RESOLVED"], ACKNOWLEDGED: ["IN_PROGRESS", "RESOLVED"], IN_PROGRESS: ["RESOLVED"], RESOLVED: ["CLOSED"], CLOSED: [] };
export function assertIncidentTransition(from: IncidentStatus, to: IncidentStatus) { if (!transitions[from]?.includes(to)) fail(`Invalid incident transition: ${from} → ${to}`); }
export async function transitionIncident(actorUserId: number, incidentId: number, toStatus: IncidentStatus, resolutionNotes?: string | null) { const current = await getIncidentById(id(incidentId)); if (!current) throw new TRPCError({ code: "NOT_FOUND", message: "Incident not found" }); assertIncidentTransition(current.status, toStatus); const now = new Date(); const incident = await updateIncident(current.id, { status: toStatus, acknowledgedAt: toStatus === "ACKNOWLEDGED" ? now : current.acknowledgedAt, resolvedAt: toStatus === "RESOLVED" ? now : current.resolvedAt, resolutionNotes: toStatus === "RESOLVED" ? resolutionNotes ?? null : current.resolutionNotes }); if (!incident) throw new TRPCError({ code: "NOT_FOUND", message: "Incident not found" }); await recordIncidentEvent(actorUserId, incident.id, `INCIDENT_${toStatus}`, current.status, toStatus, resolutionNotes ? { resolutionNotes } : {}); return incident; }
export async function assignIncident(actorUserId: number, incidentId: number, assignedToUserId: number | null) { const current = await getIncidentById(id(incidentId)); if (!current) throw new TRPCError({ code: "NOT_FOUND", message: "Incident not found" }); if (assignedToUserId !== null) { const user = await getUserById(id(assignedToUserId)); if (!user || user.status === "disabled") throw new TRPCError({ code: "BAD_REQUEST", message: "Assignee must be an active user" }); } const incident = await updateIncident(current.id, { assignedToUserId }); if (!incident) throw new TRPCError({ code: "NOT_FOUND", message: "Incident not found" }); await recordIncidentEvent(actorUserId, incident.id, "INCIDENT_ASSIGNED", current.status, current.status, { assignedToUserId }); return incident; }
