import { isIP } from "node:net";
import { TRPCError } from "@trpc/server";
import {
  createAsset, createAuditLog, createLocation, createNetworkInterface, createRelationship, createSoftware, createSoftwareInstallation,
  deleteAsset, deleteLocation, deleteNetworkInterface, deleteRelationship, deleteSoftware, deleteSoftwareInstallation,
  getAssetById, getLocationById, getNetworkInterfaceById, getSoftwareById, getSoftwareInstallationById, listAssets, listLocations,
  listNetworkInterfaces, listRelationships, listSoftware, listSoftwareInstallations, updateAsset, updateLocation, updateNetworkInterface,
  updateRelationship, updateSoftware, updateSoftwareInstallation, createNetworkDevice, deleteNetworkDevice, getNetworkDeviceByAssetId, updateNetworkDevice,
} from "../db";
import type { Asset, InsertAsset } from "../../drizzle/schema";

export const ASSET_TYPES = ["server", "workstation", "network_device"] as const;
export const ASSET_STATUSES = ["ACTIVE", "INACTIVE", "MAINTENANCE", "RETIRED", "UNKNOWN"] as const;
export const ENVIRONMENTS = ["PRODUCTION", "DEVELOPMENT", "TEST", "LAB", "OTHER"] as const;
export const RELATIONSHIP_TYPES = ["CONNECTED_TO", "DEPENDS_ON", "HOSTS", "RUNS_ON"] as const;

function badRequest(message: string): never { throw new TRPCError({ code: "BAD_REQUEST", message }); }
function notFound(message: string): never { throw new TRPCError({ code: "NOT_FOUND", message }); }
function validateHostname(hostname?: string | null) { if (hostname && !/^(?=.{1,255}$)([a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)(\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$/.test(hostname)) badRequest("hostname must be a valid DNS hostname"); }
function validateAssetInput(input: Partial<InsertAsset>) { validateHostname(input.hostname); if (input.primaryIp && !isIP(input.primaryIp)) badRequest("primaryIp must be a valid IPv4 or IPv6 address"); if (input.primaryMac && !/^([0-9A-Fa-f]{2}[:-]){5}[0-9A-Fa-f]{2}$/.test(input.primaryMac)) badRequest("primaryMac must be a valid MAC address"); if (input.cpuCores !== undefined && input.cpuCores !== null && input.cpuCores < 0) badRequest("cpuCores must be positive"); if (input.memoryMb !== undefined && input.memoryMb !== null && input.memoryMb < 0) badRequest("memoryMb must be positive"); if (input.storageGb !== undefined && input.storageGb !== null && input.storageGb < 0) badRequest("storageGb must be positive"); }
function validateInterfaceInput(input: Record<string, unknown>) { if (input.macAddress && !/^([0-9A-Fa-f]{2}[:-]){5}[0-9A-Fa-f]{2}$/.test(String(input.macAddress))) badRequest("macAddress must be a valid MAC address"); if (input.ipAddress && !isIP(String(input.ipAddress))) badRequest("ipAddress must be a valid IPv4 or IPv6 address"); if (input.prefix !== undefined && input.prefix !== null && !/^(?:[0-9]|[1-9][0-9]|1[0-2][0-9]|12[0-8])$/.test(String(input.prefix))) badRequest("prefix must be between 0 and 128"); if (input.vlan !== undefined && input.vlan !== null && (!Number.isInteger(input.vlan) || Number(input.vlan) < 1 || Number(input.vlan) > 4094)) badRequest("vlan must be between 1 and 4094"); if (input.speedMbps !== undefined && input.speedMbps !== null && Number(input.speedMbps) < 0) badRequest("speedMbps must be positive"); }
async function audit(actorUserId: number, action: string, targetId: number, targetType = "asset", metadata?: Record<string, unknown>) { await createAuditLog({ actorUserId, action, targetType, targetId: String(targetId), metadata: { ...metadata, result: "success" } }); }
async function requireAsset(id: number) { const result = await getAssetById(id); if (!result) notFound("Asset not found"); return result; }
async function requireInterface(id: number) { const result = await getNetworkInterfaceById(id); if (!result) notFound("Network interface not found"); return result; }
async function requireSoftware(id: number) { const result = await getSoftwareById(id); if (!result) notFound("Software not found"); return result; }
async function requireInstallation(id: number) { const result = await getSoftwareInstallationById(id); if (!result) notFound("Software installation not found"); return result; }
async function requireLocation(id: number) { const result = await getLocationById(id); if (!result) notFound("Location not found"); return result; }

export async function inventoryOverview() { const [all, active, maintenance, softwareRows, locationRows] = await Promise.all([listAssets({ page: 1, pageSize: 100 }), listAssets({ status: "ACTIVE", page: 1, pageSize: 100 }), listAssets({ status: "MAINTENANCE", page: 1, pageSize: 100 }), listSoftware(), listLocations()]); return { totalAssets: all.total, servers: all.items.filter(item => item.assetType === "server").length, workstations: all.items.filter(item => item.assetType === "workstation").length, networkDevices: all.items.filter(item => item.assetType === "network_device").length, activeAssets: active.total, maintenanceAssets: maintenance.total, software: softwareRows.length, locations: locationRows.length }; }
export async function readAssets(filters: Parameters<typeof listAssets>[0]) { return listAssets(filters); }
export async function readAsset(id: number) { return requireAsset(id); }
export async function createInventoryAsset(actorUserId: number, input: InsertAsset) { validateAssetInput(input); if (input.locationId !== undefined && input.locationId !== null) await requireLocation(input.locationId); const result = await createAsset(input); if (!result) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Asset could not be created" }); await audit(actorUserId, "ASSET_CREATED", result.id, "asset", { assetType: result.assetType, environment: result.environment }); return result; }
export async function updateInventoryAsset(actorUserId: number, id: number, input: Partial<InsertAsset>) { validateAssetInput(input); if (input.locationId !== undefined && input.locationId !== null) await requireLocation(input.locationId); const result = await updateAsset(id, input); if (!result) notFound("Asset not found"); await audit(actorUserId, "ASSET_UPDATED", id, "asset", { fields: Object.keys(input) }); return result; }
export async function removeInventoryAsset(actorUserId: number, id: number) { await requireAsset(id); await deleteAsset(id); await audit(actorUserId, "ASSET_DELETED", id); return { success: true }; }

export async function readLocations() { return listLocations(); }
export async function readLocation(id: number) { return requireLocation(id); }
export async function createInventoryLocation(actorUserId: number, input: Parameters<typeof createLocation>[0]) { const result = await createLocation(input); if (!result) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Location could not be created" }); await audit(actorUserId, "LOCATION_CREATED", result.id, "location"); return result; }
export async function updateInventoryLocation(actorUserId: number, id: number, input: Partial<Parameters<typeof createLocation>[0]>) { await requireLocation(id); const result = await updateLocation(id, input); if (!result) notFound("Location not found"); await audit(actorUserId, "LOCATION_UPDATED", id, "location", { fields: Object.keys(input) }); return result; }
export async function removeInventoryLocation(actorUserId: number, id: number) { await requireLocation(id); await deleteLocation(id); await audit(actorUserId, "LOCATION_DELETED", id, "location"); return { success: true }; }

export async function readNetworkInterfaces(assetId?: number) { if (assetId) await requireAsset(assetId); return listNetworkInterfaces(assetId); }
export async function readNetworkDevice(assetId: number) { await requireAsset(assetId); const result = await getNetworkDeviceByAssetId(assetId); if (!result) notFound("Network device subtype not found"); return result; }
export async function createInventoryNetworkDevice(actorUserId: number, input: { assetId: number; deviceType: string; firmware?: string | null; notes?: string | null }) { await requireAsset(input.assetId); if (!['router', 'switch', 'firewall', 'access_point', 'other'].includes(input.deviceType)) badRequest("Unsupported network device type"); const result = await createNetworkDevice(input); if (!result) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Network device subtype could not be created" }); await audit(actorUserId, "NETWORK_DEVICE_CREATED", input.assetId, "network_device", { deviceType: input.deviceType }); return result; }
export async function updateInventoryNetworkDevice(actorUserId: number, assetId: number, input: { deviceType?: string; firmware?: string | null; notes?: string | null }) { await requireAsset(assetId); if (input.deviceType && !['router', 'switch', 'firewall', 'access_point', 'other'].includes(input.deviceType)) badRequest("Unsupported network device type"); const result = await updateNetworkDevice(assetId, input); if (!result) notFound("Network device subtype not found"); await audit(actorUserId, "NETWORK_DEVICE_UPDATED", assetId, "network_device", { fields: Object.keys(input) }); return result; }
export async function removeInventoryNetworkDevice(actorUserId: number, assetId: number) { await readNetworkDevice(assetId); await deleteNetworkDevice(assetId); await audit(actorUserId, "NETWORK_DEVICE_DELETED", assetId, "network_device"); return { success: true }; }
export async function readNetworkInterface(id: number) { return requireInterface(id); }
export async function createInventoryInterface(actorUserId: number, input: Parameters<typeof createNetworkInterface>[0]) { validateInterfaceInput(input); await requireAsset(input.assetId); const result = await createNetworkInterface(input); if (!result) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Network interface could not be created" }); await audit(actorUserId, "NETWORK_INTERFACE_CREATED", result.id, "network_interface", { assetId: input.assetId }); return result; }
export async function updateInventoryInterface(actorUserId: number, id: number, input: Partial<Parameters<typeof createNetworkInterface>[0]>) { validateInterfaceInput(input); const current = await requireInterface(id); if (input.assetId !== undefined) await requireAsset(input.assetId); const result = await updateNetworkInterface(id, input); if (!result) notFound("Network interface not found"); await audit(actorUserId, "NETWORK_INTERFACE_UPDATED", id, "network_interface", { assetId: input.assetId ?? current.assetId, fields: Object.keys(input) }); return result; }
export async function removeInventoryInterface(actorUserId: number, id: number) { await requireInterface(id); await deleteNetworkInterface(id); await audit(actorUserId, "NETWORK_INTERFACE_DELETED", id, "network_interface"); return { success: true }; }

export async function readSoftware() { return listSoftware(); }
export async function readSoftwareItem(id: number) { return requireSoftware(id); }
export async function createInventorySoftware(actorUserId: number, input: Parameters<typeof createSoftware>[0]) { const result = await createSoftware(input); if (!result) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Software could not be created" }); await audit(actorUserId, "SOFTWARE_CREATED", result.id, "software"); return result; }
export async function updateInventorySoftware(actorUserId: number, id: number, input: Partial<Parameters<typeof createSoftware>[0]>) { await requireSoftware(id); const result = await updateSoftware(id, input); if (!result) notFound("Software not found"); await audit(actorUserId, "SOFTWARE_UPDATED", id, "software", { fields: Object.keys(input) }); return result; }
export async function removeInventorySoftware(actorUserId: number, id: number) { await requireSoftware(id); await deleteSoftware(id); await audit(actorUserId, "SOFTWARE_DELETED", id, "software"); return { success: true }; }

export async function readInstallations(assetId?: number, softwareId?: number) { if (assetId) await requireAsset(assetId); if (softwareId) await requireSoftware(softwareId); return listSoftwareInstallations(assetId, softwareId); }
export async function readInstallation(id: number) { return requireInstallation(id); }
export async function createInventoryInstallation(actorUserId: number, input: Parameters<typeof createSoftwareInstallation>[0]) { await requireAsset(input.assetId); await requireSoftware(input.softwareId); const result = await createSoftwareInstallation(input); if (!result) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Software installation could not be created" }); await audit(actorUserId, "SOFTWARE_INSTALLED", result.id, "software_installation", { assetId: input.assetId, softwareId: input.softwareId }); return result; }
export async function updateInventoryInstallation(actorUserId: number, id: number, input: Partial<Parameters<typeof createSoftwareInstallation>[0]>) { const current = await requireInstallation(id); if (input.assetId !== undefined) await requireAsset(input.assetId); if (input.softwareId !== undefined) await requireSoftware(input.softwareId); const result = await updateSoftwareInstallation(id, input); if (!result) notFound("Software installation not found"); await audit(actorUserId, "SOFTWARE_INSTALLATION_UPDATED", id, "software_installation", { assetId: input.assetId ?? current.assetId, softwareId: input.softwareId ?? current.softwareId, fields: Object.keys(input) }); return result; }
export async function removeInventoryInstallation(actorUserId: number, id: number) { await requireInstallation(id); await deleteSoftwareInstallation(id); await audit(actorUserId, "SOFTWARE_UNINSTALLED", id, "software_installation"); return { success: true }; }

export async function readRelationships(assetId?: number) { if (assetId) await requireAsset(assetId); return listRelationships(assetId); }
export async function createInventoryRelationship(actorUserId: number, input: Parameters<typeof createRelationship>[0]) { if (input.sourceAssetId === input.destinationAssetId) badRequest("An asset cannot relate to itself"); await requireAsset(input.sourceAssetId); await requireAsset(input.destinationAssetId); if (input.sourceInterfaceId) await requireInterface(input.sourceInterfaceId); if (input.destinationInterfaceId) await requireInterface(input.destinationInterfaceId); if (!RELATIONSHIP_TYPES.includes(input.relationshipType as typeof RELATIONSHIP_TYPES[number])) badRequest("Unsupported relationship type"); const result = await createRelationship(input); if (!result) throw new TRPCError({ code: "INTERNAL_SERVER_ERROR", message: "Relationship could not be created" }); await audit(actorUserId, "ASSET_RELATIONSHIP_CREATED", result.id, "asset_relationship", { sourceAssetId: input.sourceAssetId, destinationAssetId: input.destinationAssetId, relationshipType: input.relationshipType }); return result; }
export async function updateInventoryRelationship(actorUserId: number, id: number, input: Partial<Parameters<typeof createRelationship>[0]>) { const current = await listRelationships(); const relation = current.find(item => item.id === id); if (!relation) notFound("Relationship not found"); if (input.sourceAssetId !== undefined) await requireAsset(input.sourceAssetId); if (input.destinationAssetId !== undefined) await requireAsset(input.destinationAssetId); if (input.relationshipType !== undefined && !RELATIONSHIP_TYPES.includes(input.relationshipType as typeof RELATIONSHIP_TYPES[number])) badRequest("Unsupported relationship type"); const source = input.sourceAssetId ?? relation.sourceAssetId; const destination = input.destinationAssetId ?? relation.destinationAssetId; if (source === destination) badRequest("An asset cannot relate to itself"); const result = await updateRelationship(id, input); if (!result) notFound("Relationship not found"); await audit(actorUserId, "ASSET_RELATIONSHIP_UPDATED", id, "asset_relationship", { fields: Object.keys(input) }); return result; }
export async function removeInventoryRelationship(actorUserId: number, id: number) { const relations = await listRelationships(); if (!relations.some(item => item.id === id)) notFound("Relationship not found"); await deleteRelationship(id); await audit(actorUserId, "ASSET_RELATIONSHIP_DELETED", id, "asset_relationship"); return { success: true }; }

export function assetTypeFromPath(type: Asset["assetType"] | undefined) { return type; }
